//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaPos.Resources_String.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resCustomer_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resCustomer_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdaPos.Resources_String.Local.resCustomer_EN", typeof(resCustomer_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string tActive {
            get {
                return ResourceManager.GetString("tActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string tAddress {
            get {
                return ResourceManager.GetString("tAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address No..
        /// </summary>
        internal static string tAddressNo {
            get {
                return ResourceManager.GetString("tAddressNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        internal static string tApprove {
            get {
                return ResourceManager.GetString("tApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string tArea {
            get {
                return ResourceManager.GetString("tArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        internal static string tBranch {
            get {
                return ResourceManager.GetString("tBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Type.
        /// </summary>
        internal static string tBusinessType {
            get {
                return ResourceManager.GetString("tBusinessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expirydate.
        /// </summary>
        internal static string tCardExp {
            get {
                return ResourceManager.GetString("tCardExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued Date.
        /// </summary>
        internal static string tCardIssue {
            get {
                return ResourceManager.GetString("tCardIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card No..
        /// </summary>
        internal static string tCardNo {
            get {
                return ResourceManager.GetString("tCardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer System.
        /// </summary>
        internal static string tCardRegis {
            get {
                return ResourceManager.GetString("tCardRegis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career.
        /// </summary>
        internal static string tCareer {
            get {
                return ResourceManager.GetString("tCareer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string tContact {
            get {
                return ResourceManager.GetString("tContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usually Contact Day.
        /// </summary>
        internal static string tContactDay {
            get {
                return ResourceManager.GetString("tContactDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string tCountry {
            get {
                return ResourceManager.GetString("tCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        internal static string tCredit {
            get {
                return ResourceManager.GetString("tCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string tCst {
            get {
                return ResourceManager.GetString("tCst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeActive.
        /// </summary>
        internal static string tDeActive {
            get {
                return ResourceManager.GetString("tDeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        internal static string tDestination {
            get {
                return ResourceManager.GetString("tDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disapprove.
        /// </summary>
        internal static string tDisapprove {
            get {
                return ResourceManager.GetString("tDisapprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail Discount.
        /// </summary>
        internal static string tDisRet {
            get {
                return ResourceManager.GetString("tDisRet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        internal static string tDistrict {
            get {
                return ResourceManager.GetString("tDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whols Discount.
        /// </summary>
        internal static string tDisWhs {
            get {
                return ResourceManager.GetString("tDisWhs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        internal static string tDOB {
            get {
                return ResourceManager.GetString("tDOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string tEmail {
            get {
                return ResourceManager.GetString("tEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establishment.
        /// </summary>
        internal static string tEstab {
            get {
                return ResourceManager.GetString("tEstab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expirydate.
        /// </summary>
        internal static string tExpire {
            get {
                return ResourceManager.GetString("tExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string tFax {
            get {
                return ResourceManager.GetString("tFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string tFemale {
            get {
                return ResourceManager.GetString("tFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string tFriday {
            get {
                return ResourceManager.GetString("tFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string tGroup {
            get {
                return ResourceManager.GetString("tGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headquarters.
        /// </summary>
        internal static string tHQ {
            get {
                return ResourceManager.GetString("tHQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Card No. / Passport No..
        /// </summary>
        internal static string tIDCard {
            get {
                return ResourceManager.GetString("tIDCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual.
        /// </summary>
        internal static string tIndividual {
            get {
                return ResourceManager.GetString("tIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string tInformation {
            get {
                return ResourceManager.GetString("tInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued By.
        /// </summary>
        internal static string tIssuedBy {
            get {
                return ResourceManager.GetString("tIssuedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juristic Person.
        /// </summary>
        internal static string tJuristic {
            get {
                return ResourceManager.GetString("tJuristic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        internal static string tLatitude {
            get {
                return ResourceManager.GetString("tLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Times.
        /// </summary>
        internal static string tLeadTime {
            get {
                return ResourceManager.GetString("tLeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string tLevel {
            get {
                return ResourceManager.GetString("tLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Limit.
        /// </summary>
        internal static string tLimit {
            get {
                return ResourceManager.GetString("tLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longtitude.
        /// </summary>
        internal static string tLongtitude {
            get {
                return ResourceManager.GetString("tLongtitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Contact Date.
        /// </summary>
        internal static string tLstContact {
            get {
                return ResourceManager.GetString("tLstContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Receivced.
        /// </summary>
        internal static string tLstRcv {
            get {
                return ResourceManager.GetString("tLstRcv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Card.
        /// </summary>
        internal static string tMemberCard {
            get {
                return ResourceManager.GetString("tMemberCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Men.
        /// </summary>
        internal static string tMen {
            get {
                return ResourceManager.GetString("tMen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Code.
        /// </summary>
        internal static string tModeScan {
            get {
                return ResourceManager.GetString("tModeScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string tModeSearch {
            get {
                return ResourceManager.GetString("tModeSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string tMonday {
            get {
                return ResourceManager.GetString("tMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not select new customers if there are some items on the bil.
        /// </summary>
        internal static string tMsgCantSelectCst {
            get {
                return ResourceManager.GetString("tMsgCantSelectCst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference price level cannot change (just change by cancel document).
        /// </summary>
        internal static string tMsgDiffPriLev {
            get {
                return ResourceManager.GetString("tMsgDiffPriLev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This QR code is expired.
        /// </summary>
        internal static string tMsgQRExpire {
            get {
                return ResourceManager.GetString("tMsgQRExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid QR code format.
        /// </summary>
        internal static string tMsgQRFmt {
            get {
                return ResourceManager.GetString("tMsgQRFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Name.
        /// </summary>
        internal static string tNameOther {
            get {
                return ResourceManager.GetString("tNameOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Condition.
        /// </summary>
        internal static string tPayCdt {
            get {
                return ResourceManager.GetString("tPayCdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        internal static string tPayment {
            get {
                return ResourceManager.GetString("tPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion Group.
        /// </summary>
        internal static string tPmtGrp {
            get {
                return ResourceManager.GetString("tPmtGrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point.
        /// </summary>
        internal static string tPoint {
            get {
                return ResourceManager.GetString("tPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode.
        /// </summary>
        internal static string tPostcode {
            get {
                return ResourceManager.GetString("tPostcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Group.
        /// </summary>
        internal static string tPriGrp {
            get {
                return ResourceManager.GetString("tPriGrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Level.
        /// </summary>
        internal static string tPriLevel {
            get {
                return ResourceManager.GetString("tPriLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        internal static string tProvince {
            get {
                return ResourceManager.GetString("tProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        internal static string tRemark {
            get {
                return ResourceManager.GetString("tRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID.
        /// </summary>
        internal static string tRFID {
            get {
                return ResourceManager.GetString("tRFID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road.
        /// </summary>
        internal static string tRoad {
            get {
                return ResourceManager.GetString("tRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Person.
        /// </summary>
        internal static string tSalePerson {
            get {
                return ResourceManager.GetString("tSalePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string tSaturday {
            get {
                return ResourceManager.GetString("tSaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string tSearch {
            get {
                return ResourceManager.GetString("tSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Search.
        /// </summary>
        internal static string tSearchLocation {
            get {
                return ResourceManager.GetString("tSearchLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        internal static string tSex {
            get {
                return ResourceManager.GetString("tSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship By.
        /// </summary>
        internal static string tShipBy {
            get {
                return ResourceManager.GetString("tShipBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Condition.
        /// </summary>
        internal static string tShippingCdt {
            get {
                return ResourceManager.GetString("tShippingCdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press button search for show data.
        /// </summary>
        internal static string tShowData {
            get {
                return ResourceManager.GetString("tShowData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soi.
        /// </summary>
        internal static string tSoi {
            get {
                return ResourceManager.GetString("tSoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string tSource {
            get {
                return ResourceManager.GetString("tSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Status.
        /// </summary>
        internal static string tStaActive {
            get {
                return ResourceManager.GetString("tStaActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve Status.
        /// </summary>
        internal static string tStaApprove {
            get {
                return ResourceManager.GetString("tStaApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Status.
        /// </summary>
        internal static string tStaContact {
            get {
                return ResourceManager.GetString("tStaContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement Condition.
        /// </summary>
        internal static string tStatementCdt {
            get {
                return ResourceManager.GetString("tStatementCdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub - District.
        /// </summary>
        internal static string tSubDistrict {
            get {
                return ResourceManager.GetString("tSubDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string tSunday {
            get {
                return ResourceManager.GetString("tSunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax ID.
        /// </summary>
        internal static string tTax {
            get {
                return ResourceManager.GetString("tTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        internal static string tTelephone {
            get {
                return ResourceManager.GetString("tTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Term (Days).
        /// </summary>
        internal static string tTerm {
            get {
                return ResourceManager.GetString("tTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string tThursday {
            get {
                return ResourceManager.GetString("tThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Amt. :.
        /// </summary>
        internal static string tTitelQRPayAmt {
            get {
                return ResourceManager.GetString("tTitelQRPayAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Card No :.
        /// </summary>
        internal static string tTitleQRCardID {
            get {
                return ResourceManager.GetString("tTitleQRCardID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name :.
        /// </summary>
        internal static string tTitleQRName {
            get {
                return ResourceManager.GetString("tTitleQRName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcel Code :.
        /// </summary>
        internal static string tTitleQRParcel {
            get {
                return ResourceManager.GetString("tTitleQRParcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref. Code :.
        /// </summary>
        internal static string tTitleQRRefCode {
            get {
                return ResourceManager.GetString("tTitleQRRefCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone No :.
        /// </summary>
        internal static string tTitleQRTel {
            get {
                return ResourceManager.GetString("tTitleQRTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please scan QR Code.
        /// </summary>
        internal static string tTitleScanQR {
            get {
                return ResourceManager.GetString("tTitleScanQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string tTuesday {
            get {
                return ResourceManager.GetString("tTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string tType {
            get {
                return ResourceManager.GetString("tType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responed By.
        /// </summary>
        internal static string tUser {
            get {
                return ResourceManager.GetString("tUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tVillage.
        /// </summary>
        internal static string tVillage {
            get {
                return ResourceManager.GetString("tVillage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string tWebsite {
            get {
                return ResourceManager.GetString("tWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string tWednesday {
            get {
                return ResourceManager.GetString("tWednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone.
        /// </summary>
        internal static string tZone {
            get {
                return ResourceManager.GetString("tZone", resourceCulture);
            }
        }
    }
}
