//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaPos.Resources_String.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resChangeWristband_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resChangeWristband_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdaPos.Resources_String.Local.resChangeWristband_EN", typeof(resChangeWristband_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card / Change wristband.
        /// </summary>
        internal static string tChange {
            get {
                return ResourceManager.GetString("tChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string tChgWsbAvailable {
            get {
                return ResourceManager.GetString("tChgWsbAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Expire.
        /// </summary>
        internal static string tChgWsbDateExp {
            get {
                return ResourceManager.GetString("tChgWsbDateExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        internal static string tChgWsbDeposit {
            get {
                return ResourceManager.GetString("tChgWsbDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        internal static string tChgWsbMode {
            get {
                return ResourceManager.GetString("tChgWsbMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input new card no. / wristband no..
        /// </summary>
        internal static string tChgWsbMsgInputNewWristband {
            get {
                return ResourceManager.GetString("tChgWsbMsgInputNewWristband", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input card no. / wristband no..
        /// </summary>
        internal static string tChgWsbMsgInputWristband {
            get {
                return ResourceManager.GetString("tChgWsbMsgInputWristband", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Name / Wristband Name.
        /// </summary>
        internal static string tChgWsbName {
            get {
                return ResourceManager.GetString("tChgWsbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Card No. / Wristband No..
        /// </summary>
        internal static string tChgWsbNewWBNo {
            get {
                return ResourceManager.GetString("tChgWsbNewWBNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process false..
        /// </summary>
        internal static string tChgWsbPrcFalse {
            get {
                return ResourceManager.GetString("tChgWsbPrcFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process success..
        /// </summary>
        internal static string tChgWsbPrcSuccess {
            get {
                return ResourceManager.GetString("tChgWsbPrcSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Card.
        /// </summary>
        internal static string tChgWsbPrnChgCrd {
            get {
                return ResourceManager.GetString("tChgWsbPrnChgCrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form {0}.
        /// </summary>
        internal static string tChgWsbPrnCrdFrm {
            get {
                return ResourceManager.GetString("tChgWsbPrnCrdFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card No..
        /// </summary>
        internal static string tChgWsbPrnCrdNo {
            get {
                return ResourceManager.GetString("tChgWsbPrnCrdNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To {0}.
        /// </summary>
        internal static string tChgWsbPrnCrdTo {
            get {
                return ResourceManager.GetString("tChgWsbPrnCrdTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket No..
        /// </summary>
        internal static string tChgWsbTKNo {
            get {
                return ResourceManager.GetString("tChgWsbTKNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Type / Wristband Type.
        /// </summary>
        internal static string tChgWsbType {
            get {
                return ResourceManager.GetString("tChgWsbType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Value / Wristband Value.
        /// </summary>
        internal static string tChgWsbValue {
            get {
                return ResourceManager.GetString("tChgWsbValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card No. / Wristband No..
        /// </summary>
        internal static string tChgWsbWBNo {
            get {
                return ResourceManager.GetString("tChgWsbWBNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card / Wristband.
        /// </summary>
        internal static string tModeCrdOrWristband {
            get {
                return ResourceManager.GetString("tModeCrdOrWristband", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket.
        /// </summary>
        internal static string tModeTicket {
            get {
                return ResourceManager.GetString("tModeTicket", resourceCulture);
            }
        }
    }
}
