//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaPos.Resources_String.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resCloseShift_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resCloseShift_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdaPos.Resources_String.Local.resCloseShift_EN", typeof(resCloseShift_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banknote.
        /// </summary>
        internal static string tBanknote {
            get {
                return ResourceManager.GetString("tBanknote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Close.
        /// </summary>
        internal static string tCloseDate {
            get {
                return ResourceManager.GetString("tCloseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close shift.
        /// </summary>
        internal static string tCloseShift {
            get {
                return ResourceManager.GetString("tCloseShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwod.
        /// </summary>
        internal static string tMode1 {
            get {
                return ResourceManager.GetString("tMode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Code.
        /// </summary>
        internal static string tMode2 {
            get {
                return ResourceManager.GetString("tMode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID.
        /// </summary>
        internal static string tMode3 {
            get {
                return ResourceManager.GetString("tMode3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of payment.
        /// </summary>
        internal static string tPayType {
            get {
                return ResourceManager.GetString("tPayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Code.
        /// </summary>
        internal static string tShiftCode {
            get {
                return ResourceManager.GetString("tShiftCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last User :.
        /// </summary>
        internal static string tTitleLastUsr {
            get {
                return ResourceManager.GetString("tTitleLastUsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Detail.
        /// </summary>
        internal static string tTitleShiftDetail {
            get {
                return ResourceManager.GetString("tTitleShiftDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In :.
        /// </summary>
        internal static string tTitleSignIn {
            get {
                return ResourceManager.GetString("tTitleSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out :.
        /// </summary>
        internal static string tTitleSignOut {
            get {
                return ResourceManager.GetString("tTitleSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string tTitleTotal {
            get {
                return ResourceManager.GetString("tTitleTotal", resourceCulture);
            }
        }
    }
}
