//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaPos.Resources_String.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resCustomer_TH {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resCustomer_TH() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdaPos.Resources_String.Local.resCustomer_TH", typeof(resCustomer_TH).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ติดต่อ.
        /// </summary>
        internal static string tActive {
            get {
                return ResourceManager.GetString("tActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่อยู่.
        /// </summary>
        internal static string tAddress {
            get {
                return ResourceManager.GetString("tAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บ้านเลขที่.
        /// </summary>
        internal static string tAddressNo {
            get {
                return ResourceManager.GetString("tAddressNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อนุมัติ.
        /// </summary>
        internal static string tApprove {
            get {
                return ResourceManager.GetString("tApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ภูมิภาค.
        /// </summary>
        internal static string tArea {
            get {
                return ResourceManager.GetString("tArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สาขา.
        /// </summary>
        internal static string tBranch {
            get {
                return ResourceManager.GetString("tBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทธุรกิจ.
        /// </summary>
        internal static string tBusinessType {
            get {
                return ResourceManager.GetString("tBusinessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันหมดอายุ.
        /// </summary>
        internal static string tCardExp {
            get {
                return ResourceManager.GetString("tCardExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่ออกบัตร.
        /// </summary>
        internal static string tCardIssue {
            get {
                return ResourceManager.GetString("tCardIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเลขบัตร.
        /// </summary>
        internal static string tCardNo {
            get {
                return ResourceManager.GetString("tCardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่สมัคร.
        /// </summary>
        internal static string tCardRegis {
            get {
                return ResourceManager.GetString("tCardRegis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อาชีพ.
        /// </summary>
        internal static string tCareer {
            get {
                return ResourceManager.GetString("tCareer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลติดต่อ.
        /// </summary>
        internal static string tContact {
            get {
                return ResourceManager.GetString("tContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันติดต่อประจำ.
        /// </summary>
        internal static string tContactDay {
            get {
                return ResourceManager.GetString("tContactDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเทศ.
        /// </summary>
        internal static string tCountry {
            get {
                return ResourceManager.GetString("tCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เครดิต.
        /// </summary>
        internal static string tCredit {
            get {
                return ResourceManager.GetString("tCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลูกค้า.
        /// </summary>
        internal static string tCst {
            get {
                return ResourceManager.GetString("tCst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยกเลิกติดต่อ.
        /// </summary>
        internal static string tDeActive {
            get {
                return ResourceManager.GetString("tDeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ปลายทาง.
        /// </summary>
        internal static string tDestination {
            get {
                return ResourceManager.GetString("tDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่อนุมัติ.
        /// </summary>
        internal static string tDisapprove {
            get {
                return ResourceManager.GetString("tDisapprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่วนลดขายปลีก.
        /// </summary>
        internal static string tDisRet {
            get {
                return ResourceManager.GetString("tDisRet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เขต / อำเภอ.
        /// </summary>
        internal static string tDistrict {
            get {
                return ResourceManager.GetString("tDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่วนลดขายส่ง.
        /// </summary>
        internal static string tDisWhs {
            get {
                return ResourceManager.GetString("tDisWhs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันเกิด.
        /// </summary>
        internal static string tDOB {
            get {
                return ResourceManager.GetString("tDOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อีเมล.
        /// </summary>
        internal static string tEmail {
            get {
                return ResourceManager.GetString("tEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานประกอบการ.
        /// </summary>
        internal static string tEstab {
            get {
                return ResourceManager.GetString("tEstab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันหมดอายุ.
        /// </summary>
        internal static string tExpire {
            get {
                return ResourceManager.GetString("tExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โทรสาร.
        /// </summary>
        internal static string tFax {
            get {
                return ResourceManager.GetString("tFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้หญิง.
        /// </summary>
        internal static string tFemale {
            get {
                return ResourceManager.GetString("tFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันศุกร์.
        /// </summary>
        internal static string tFriday {
            get {
                return ResourceManager.GetString("tFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กลุ่ม.
        /// </summary>
        internal static string tGroup {
            get {
                return ResourceManager.GetString("tGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สำนักงานใหญ่.
        /// </summary>
        internal static string tHQ {
            get {
                return ResourceManager.GetString("tHQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บัตรประชาชน / พาสปอร์ต.
        /// </summary>
        internal static string tIDCard {
            get {
                return ResourceManager.GetString("tIDCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บุคคลธรรมดา.
        /// </summary>
        internal static string tIndividual {
            get {
                return ResourceManager.GetString("tIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลทั่วไป.
        /// </summary>
        internal static string tInformation {
            get {
                return ResourceManager.GetString("tInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ออกโดย.
        /// </summary>
        internal static string tIssuedBy {
            get {
                return ResourceManager.GetString("tIssuedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นิติบุคคล.
        /// </summary>
        internal static string tJuristic {
            get {
                return ResourceManager.GetString("tJuristic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ละติจูด.
        /// </summary>
        internal static string tLatitude {
            get {
                return ResourceManager.GetString("tLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนวันขนส่ง.
        /// </summary>
        internal static string tLeadTime {
            get {
                return ResourceManager.GetString("tLeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระดับ.
        /// </summary>
        internal static string tLevel {
            get {
                return ResourceManager.GetString("tLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วงเงินเครดิต.
        /// </summary>
        internal static string tLimit {
            get {
                return ResourceManager.GetString("tLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลองจิจูด.
        /// </summary>
        internal static string tLongtitude {
            get {
                return ResourceManager.GetString("tLongtitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่ติดต่อล่าสุด.
        /// </summary>
        internal static string tLstContact {
            get {
                return ResourceManager.GetString("tLstContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รับชำระล่าสุด.
        /// </summary>
        internal static string tLstRcv {
            get {
                return ResourceManager.GetString("tLstRcv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บัตรสมาชิก.
        /// </summary>
        internal static string tMemberCard {
            get {
                return ResourceManager.GetString("tMemberCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้ชาย.
        /// </summary>
        internal static string tMen {
            get {
                return ResourceManager.GetString("tMen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สแกนคิวอาร์โค้ด.
        /// </summary>
        internal static string tModeScan {
            get {
                return ResourceManager.GetString("tModeScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค้นหา.
        /// </summary>
        internal static string tModeSearch {
            get {
                return ResourceManager.GetString("tModeSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันจันทร์.
        /// </summary>
        internal static string tMonday {
            get {
                return ResourceManager.GetString("tMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มีการทำรายการค้างอยู่ ไม่สามารถเลือกลูกค้าใหม่ได้.
        /// </summary>
        internal static string tMsgCantSelectCst {
            get {
                return ResourceManager.GetString("tMsgCantSelectCst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระดับราคาขายต่างกัน ไม่สามารถแก้ไขได้(เปลี่ยนโดยการยกเลิกเอกสาร อย่างเดียว).
        /// </summary>
        internal static string tMsgDiffPriLev {
            get {
                return ResourceManager.GetString("tMsgDiffPriLev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คิวอาร์โค้ดนี้หมดอายุแล้ว.
        /// </summary>
        internal static string tMsgQRExpire {
            get {
                return ResourceManager.GetString("tMsgQRExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รูปแบบคิวอาร์โค้ดไม่ถูกต้อง.
        /// </summary>
        internal static string tMsgQRFmt {
            get {
                return ResourceManager.GetString("tMsgQRFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่ออื่น.
        /// </summary>
        internal static string tNameOther {
            get {
                return ResourceManager.GetString("tNameOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เงื่อนไขชำระเงิน.
        /// </summary>
        internal static string tPayCdt {
            get {
                return ResourceManager.GetString("tPayCdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชำระเงิน.
        /// </summary>
        internal static string tPayment {
            get {
                return ResourceManager.GetString("tPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กลุ่มโปรโมชั่น.
        /// </summary>
        internal static string tPmtGrp {
            get {
                return ResourceManager.GetString("tPmtGrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แต้ม.
        /// </summary>
        internal static string tPoint {
            get {
                return ResourceManager.GetString("tPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสไปรษณีย์.
        /// </summary>
        internal static string tPostcode {
            get {
                return ResourceManager.GetString("tPostcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กลุ่มราคา.
        /// </summary>
        internal static string tPriGrp {
            get {
                return ResourceManager.GetString("tPriGrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระดับราคา.
        /// </summary>
        internal static string tPriLevel {
            get {
                return ResourceManager.GetString("tPriLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จังหวัด.
        /// </summary>
        internal static string tProvince {
            get {
                return ResourceManager.GetString("tProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเหตุ.
        /// </summary>
        internal static string tRemark {
            get {
                return ResourceManager.GetString("tRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID.
        /// </summary>
        internal static string tRFID {
            get {
                return ResourceManager.GetString("tRFID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ถนน.
        /// </summary>
        internal static string tRoad {
            get {
                return ResourceManager.GetString("tRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พนักงานขาย.
        /// </summary>
        internal static string tSalePerson {
            get {
                return ResourceManager.GetString("tSalePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันเสาร์.
        /// </summary>
        internal static string tSaturday {
            get {
                return ResourceManager.GetString("tSaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค้นหา.
        /// </summary>
        internal static string tSearch {
            get {
                return ResourceManager.GetString("tSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค้นหาสถานที่.
        /// </summary>
        internal static string tSearchLocation {
            get {
                return ResourceManager.GetString("tSearchLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพศ.
        /// </summary>
        internal static string tSex {
            get {
                return ResourceManager.GetString("tSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขนส่งโดย.
        /// </summary>
        internal static string tShipBy {
            get {
                return ResourceManager.GetString("tShipBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เงื่อนไขขนส่ง.
        /// </summary>
        internal static string tShippingCdt {
            get {
                return ResourceManager.GetString("tShippingCdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กดปุ่มค้นหาเพื่อโชว์ข้อมูล.
        /// </summary>
        internal static string tShowData {
            get {
                return ResourceManager.GetString("tShowData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ซอย.
        /// </summary>
        internal static string tSoi {
            get {
                return ResourceManager.GetString("tSoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ต้นทาง.
        /// </summary>
        internal static string tSource {
            get {
                return ResourceManager.GetString("tSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานะใช้งาน.
        /// </summary>
        internal static string tStaActive {
            get {
                return ResourceManager.GetString("tStaActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานะอนุมัติ.
        /// </summary>
        internal static string tStaApprove {
            get {
                return ResourceManager.GetString("tStaApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานะการติดต่อ.
        /// </summary>
        internal static string tStaContact {
            get {
                return ResourceManager.GetString("tStaContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เงื่อนไขวางบิล.
        /// </summary>
        internal static string tStatementCdt {
            get {
                return ResourceManager.GetString("tStatementCdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แขวง / ตำบล.
        /// </summary>
        internal static string tSubDistrict {
            get {
                return ResourceManager.GetString("tSubDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันอาทิตย์.
        /// </summary>
        internal static string tSunday {
            get {
                return ResourceManager.GetString("tSunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขประจำตัวผู้เสียภาษี.
        /// </summary>
        internal static string tTax {
            get {
                return ResourceManager.GetString("tTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเลขโทรศัพท์.
        /// </summary>
        internal static string tTelephone {
            get {
                return ResourceManager.GetString("tTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เครดิต (วัน).
        /// </summary>
        internal static string tTerm {
            get {
                return ResourceManager.GetString("tTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันพฤหัสบดี.
        /// </summary>
        internal static string tThursday {
            get {
                return ResourceManager.GetString("tThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอดชำระ :.
        /// </summary>
        internal static string tTitelQRPayAmt {
            get {
                return ResourceManager.GetString("tTitelQRPayAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสบัตรประจำตัว :.
        /// </summary>
        internal static string tTitleQRCardID {
            get {
                return ResourceManager.GetString("tTitleQRCardID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อ - สกุล :.
        /// </summary>
        internal static string tTitleQRName {
            get {
                return ResourceManager.GetString("tTitleQRName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสพัสดุ :.
        /// </summary>
        internal static string tTitleQRParcel {
            get {
                return ResourceManager.GetString("tTitleQRParcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสอ้างอิง :.
        /// </summary>
        internal static string tTitleQRRefCode {
            get {
                return ResourceManager.GetString("tTitleQRRefCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เบอร์โทรศัพท์ :.
        /// </summary>
        internal static string tTitleQRTel {
            get {
                return ResourceManager.GetString("tTitleQRTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาสแกนคิวอาร์โค้ด.
        /// </summary>
        internal static string tTitleScanQR {
            get {
                return ResourceManager.GetString("tTitleScanQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันอังคาร.
        /// </summary>
        internal static string tTuesday {
            get {
                return ResourceManager.GetString("tTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภท.
        /// </summary>
        internal static string tType {
            get {
                return ResourceManager.GetString("tType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้รับผิดชอบ.
        /// </summary>
        internal static string tUser {
            get {
                return ResourceManager.GetString("tUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมู่บ้าน.
        /// </summary>
        internal static string tVillage {
            get {
                return ResourceManager.GetString("tVillage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เว็บไซต์.
        /// </summary>
        internal static string tWebsite {
            get {
                return ResourceManager.GetString("tWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันพุธ.
        /// </summary>
        internal static string tWednesday {
            get {
                return ResourceManager.GetString("tWednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โซน.
        /// </summary>
        internal static string tZone {
            get {
                return ResourceManager.GetString("tZone", resourceCulture);
            }
        }
    }
}
