//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaPos.Resources_String.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resChangeWristband_TH {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resChangeWristband_TH() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdaPos.Resources_String.Local.resChangeWristband_TH", typeof(resChangeWristband_TH).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เปลี่ยนบัตร / ริสแบนด์.
        /// </summary>
        internal static string tChange {
            get {
                return ResourceManager.GetString("tChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มูลค่าที่ใช้ได้.
        /// </summary>
        internal static string tChgWsbAvailable {
            get {
                return ResourceManager.GetString("tChgWsbAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันหมดอายุ.
        /// </summary>
        internal static string tChgWsbDateExp {
            get {
                return ResourceManager.GetString("tChgWsbDateExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค่ามัดจำ.
        /// </summary>
        internal static string tChgWsbDeposit {
            get {
                return ResourceManager.GetString("tChgWsbDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โหมด.
        /// </summary>
        internal static string tChgWsbMode {
            get {
                return ResourceManager.GetString("tChgWsbMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกหมายเลขบัตรใหม่ / ริชแบนด์.
        /// </summary>
        internal static string tChgWsbMsgInputNewWristband {
            get {
                return ResourceManager.GetString("tChgWsbMsgInputNewWristband", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกหมายเลขบัตร / ริชแบนด์.
        /// </summary>
        internal static string tChgWsbMsgInputWristband {
            get {
                return ResourceManager.GetString("tChgWsbMsgInputWristband", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อบัตร / ริสแบนด์.
        /// </summary>
        internal static string tChgWsbName {
            get {
                return ResourceManager.GetString("tChgWsbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเลขบัตรใหม่ / ริสแบนด์.
        /// </summary>
        internal static string tChgWsbNewWBNo {
            get {
                return ResourceManager.GetString("tChgWsbNewWBNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถทำรายการได้.
        /// </summary>
        internal static string tChgWsbPrcFalse {
            get {
                return ResourceManager.GetString("tChgWsbPrcFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทำรายการสำเร็จ.
        /// </summary>
        internal static string tChgWsbPrcSuccess {
            get {
                return ResourceManager.GetString("tChgWsbPrcSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เปลี่ยนบัตร.
        /// </summary>
        internal static string tChgWsbPrnChgCrd {
            get {
                return ResourceManager.GetString("tChgWsbPrnChgCrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จาก {0}.
        /// </summary>
        internal static string tChgWsbPrnCrdFrm {
            get {
                return ResourceManager.GetString("tChgWsbPrnCrdFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเลขบัตร.
        /// </summary>
        internal static string tChgWsbPrnCrdNo {
            get {
                return ResourceManager.GetString("tChgWsbPrnCrdNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เป็น {0}.
        /// </summary>
        internal static string tChgWsbPrnCrdTo {
            get {
                return ResourceManager.GetString("tChgWsbPrnCrdTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเลขตั๋ว.
        /// </summary>
        internal static string tChgWsbTKNo {
            get {
                return ResourceManager.GetString("tChgWsbTKNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทบัตร / ริสแบนด์.
        /// </summary>
        internal static string tChgWsbType {
            get {
                return ResourceManager.GetString("tChgWsbType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มูลค่าบัตร / ริสแบนด์.
        /// </summary>
        internal static string tChgWsbValue {
            get {
                return ResourceManager.GetString("tChgWsbValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเลขบัตร / ริสแบนด์.
        /// </summary>
        internal static string tChgWsbWBNo {
            get {
                return ResourceManager.GetString("tChgWsbWBNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บัตร / ริชแบนด์.
        /// </summary>
        internal static string tModeCrdOrWristband {
            get {
                return ResourceManager.GetString("tModeCrdOrWristband", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตั๋ว.
        /// </summary>
        internal static string tModeTicket {
            get {
                return ResourceManager.GetString("tModeTicket", resourceCulture);
            }
        }
    }
}
