//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaPos.Resources_String.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resDiscount_TH {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resDiscount_TH() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdaPos.Resources_String.Local.resDiscount_TH", typeof(resDiscount_TH).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หลังชาร์จจำนวน.
        /// </summary>
        internal static string olaAfChgAmt {
            get {
                return ResourceManager.GetString("olaAfChgAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หลังชาร์จเปอร์เซ็นต์.
        /// </summary>
        internal static string olaAfChgPer {
            get {
                return ResourceManager.GetString("olaAfChgPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หลังหักส่วนลด.
        /// </summary>
        internal static string olaAfDisAmt {
            get {
                return ResourceManager.GetString("olaAfDisAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หลังหักส่วนลดเปอร์เซ็นต์.
        /// </summary>
        internal static string olaAfDisPer {
            get {
                return ResourceManager.GetString("olaAfDisPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวน.
        /// </summary>
        internal static string olaAmount {
            get {
                return ResourceManager.GetString("olaAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนเปอร์เซ็นต์.
        /// </summary>
        internal static string olaAmountPer {
            get {
                return ResourceManager.GetString("olaAmountPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ก่อนชาร์จจำนวน.
        /// </summary>
        internal static string olaB4ChgAmt {
            get {
                return ResourceManager.GetString("olaB4ChgAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ก่อนชาร์จเปอร์เซ็นต์.
        /// </summary>
        internal static string olaB4ChgPer {
            get {
                return ResourceManager.GetString("olaB4ChgPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ก่อนหักส่วนลด.
        /// </summary>
        internal static string olaB4DisAmt {
            get {
                return ResourceManager.GetString("olaB4DisAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ก่อนหักส่วนลดเปอร์เซ็นต์.
        /// </summary>
        internal static string olaB4DisPer {
            get {
                return ResourceManager.GetString("olaB4DisPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนชาร์จ.
        /// </summary>
        internal static string olaChgAmt {
            get {
                return ResourceManager.GetString("olaChgAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เปอร์เซ็นต์ชาร์จ.
        /// </summary>
        internal static string olaChgPer {
            get {
                return ResourceManager.GetString("olaChgPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนส่วนลด.
        /// </summary>
        internal static string olaDisAmt {
            get {
                return ResourceManager.GetString("olaDisAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เปอร์เซ็นต์ส่วนลด.
        /// </summary>
        internal static string olaDisPer {
            get {
                return ResourceManager.GetString("olaDisPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เหตุผลการลด.
        /// </summary>
        internal static string olaReason {
            get {
                return ResourceManager.GetString("olaReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เหตุผลการชาร์จ.
        /// </summary>
        internal static string olaReasonChg {
            get {
                return ResourceManager.GetString("olaReasonChg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลดราคาต้องไม่ต่ำกว่า 0 บาท.
        /// </summary>
        internal static string tDisLess {
            get {
                return ResourceManager.GetString("tDisLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใส่ค่าเป็นตัวเลขเท่านั้น.
        /// </summary>
        internal static string tIsNumberOnly {
            get {
                return ResourceManager.GetString("tIsNumberOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใส่ค่าเปอร์เซ็นต์ไม่ถูกต้อง กรุณาใส่ใหม่.
        /// </summary>
        internal static string tMsgNoPercen {
            get {
                return ResourceManager.GetString("tMsgNoPercen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกเหตุผลการลด / ชาร์จ.
        /// </summary>
        internal static string tMsgNotChooseRsn {
            get {
                return ResourceManager.GetString("tMsgNotChooseRsn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกเหตุผลการชาร์จ.
        /// </summary>
        internal static string tMsgNotChooseRsnChg {
            get {
                return ResourceManager.GetString("tMsgNotChooseRsnChg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกเหตุผลการลด.
        /// </summary>
        internal static string tMsgNotChooseRsnDis {
            get {
                return ResourceManager.GetString("tMsgNotChooseRsnDis", resourceCulture);
            }
        }
    }
}
