//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaPos.Resources_String.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resDashboard_TH {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resDashboard_TH() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdaPos.Resources_String.Local.resDashboard_TH", typeof(resDashboard_TH).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กำหนดเอง.
        /// </summary>
        internal static string tFilterCustom {
            get {
                return ResourceManager.GetString("tFilterCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ย้อนหลัง 30 วัน.
        /// </summary>
        internal static string tFilterLast30Days {
            get {
                return ResourceManager.GetString("tFilterLast30Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ย้อนหลัง 7 วัน.
        /// </summary>
        internal static string tFilterLast7Days {
            get {
                return ResourceManager.GetString("tFilterLast7Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เดือนที่แล้ว.
        /// </summary>
        internal static string tFilterLastMonth {
            get {
                return ResourceManager.GetString("tFilterLastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แสดงตามบิล.
        /// </summary>
        internal static string tFilterShwByBill {
            get {
                return ResourceManager.GetString("tFilterShwByBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แสดงตามสินค้า.
        /// </summary>
        internal static string tFilterShwByPdt {
            get {
                return ResourceManager.GetString("tFilterShwByPdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แสดงตามการชำระเงิน.
        /// </summary>
        internal static string tFilterShwByRcv {
            get {
                return ResourceManager.GetString("tFilterShwByRcv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เดือนนี้.
        /// </summary>
        internal static string tFilterThisMonth {
            get {
                return ResourceManager.GetString("tFilterThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันนี้.
        /// </summary>
        internal static string tFilterToday {
            get {
                return ResourceManager.GetString("tFilterToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เมื่อวาน.
        /// </summary>
        internal static string tFilterYesterday {
            get {
                return ResourceManager.GetString("tFilterYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มีภาษี.
        /// </summary>
        internal static string tHasVat {
            get {
                return ResourceManager.GetString("tHasVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่งออก CSV สำเร็จ.
        /// </summary>
        internal static string tMsgExpSuccess {
            get {
                return ResourceManager.GetString("tMsgExpSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่มีภาษี.
        /// </summary>
        internal static string tNoVat {
            get {
                return ResourceManager.GetString("tNoVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คืน.
        /// </summary>
        internal static string tReturn {
            get {
                return ResourceManager.GetString("tReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขาย.
        /// </summary>
        internal static string tSale {
            get {
                return ResourceManager.GetString("tSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แดชบอร์ด.
        /// </summary>
        internal static string tTitle {
            get {
                return ResourceManager.GetString("tTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มูลค่ายอดคืน.
        /// </summary>
        internal static string tTitleAmtReturn {
            get {
                return ResourceManager.GetString("tTitleAmtReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มูลค่ายอดขาย.
        /// </summary>
        internal static string tTitleAmtSale {
            get {
                return ResourceManager.GetString("tTitleAmtSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มูลค่ารวม.
        /// </summary>
        internal static string tTitleAmtTotal {
            get {
                return ResourceManager.GetString("tTitleAmtTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่งออก CSV.
        /// </summary>
        internal static string tTitleExpCSV {
            get {
                return ResourceManager.GetString("tTitleExpCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอดรวม.
        /// </summary>
        internal static string tTitleHDAmtTotal {
            get {
                return ResourceManager.GetString("tTitleHDAmtTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสบาร์โค้ด.
        /// </summary>
        internal static string tTitleHDBarCode {
            get {
                return ResourceManager.GetString("tTitleHDBarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่ขาย.
        /// </summary>
        internal static string tTitleHDDateSale {
            get {
                return ResourceManager.GetString("tTitleHDDateSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่วนลด.
        /// </summary>
        internal static string tTitleHDDisChg {
            get {
                return ResourceManager.GetString("tTitleHDDisChg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขที่เอกสาร.
        /// </summary>
        internal static string tTitleHDDocNo {
            get {
                return ResourceManager.GetString("tTitleHDDocNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทเอกสาร.
        /// </summary>
        internal static string tTitleHDDocType {
            get {
                return ResourceManager.GetString("tTitleHDDocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอดสุทธิ.
        /// </summary>
        internal static string tTitleHDNet {
            get {
                return ResourceManager.GetString("tTitleHDNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสสินค้า.
        /// </summary>
        internal static string tTitleHDPdtCode {
            get {
                return ResourceManager.GetString("tTitleHDPdtCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อสินค้า.
        /// </summary>
        internal static string tTitleHDPdtName {
            get {
                return ResourceManager.GetString("tTitleHDPdtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หน่วย.
        /// </summary>
        internal static string tTitleHDPunName {
            get {
                return ResourceManager.GetString("tTitleHDPunName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวน.
        /// </summary>
        internal static string tTitleHDQty {
            get {
                return ResourceManager.GetString("tTitleHDQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอดชำระ.
        /// </summary>
        internal static string tTitleHDRcvNet {
            get {
                return ResourceManager.GetString("tTitleHDRcvNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อ้างอิงชำระ1.
        /// </summary>
        internal static string tTitleHDRcvRef1 {
            get {
                return ResourceManager.GetString("tTitleHDRcvRef1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อ้างอิงชำระ2.
        /// </summary>
        internal static string tTitleHDRcvRef2 {
            get {
                return ResourceManager.GetString("tTitleHDRcvRef2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทชำระ.
        /// </summary>
        internal static string tTitleHDRcvType {
            get {
                return ResourceManager.GetString("tTitleHDRcvType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอดปัดเศษ.
        /// </summary>
        internal static string tTitleHDRnd {
            get {
                return ResourceManager.GetString("tTitleHDRnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลำดับ.
        /// </summary>
        internal static string tTitleHDSeq {
            get {
                return ResourceManager.GetString("tTitleHDSeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ภาษี.
        /// </summary>
        internal static string tTitleHDVat {
            get {
                return ResourceManager.GetString("tTitleHDVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ก่อนภาษี.
        /// </summary>
        internal static string tTitleHDVatable {
            get {
                return ResourceManager.GetString("tTitleHDVatable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานะภาษี.
        /// </summary>
        internal static string tTitleHDVatType {
            get {
                return ResourceManager.GetString("tTitleHDVatType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนบิลคืน.
        /// </summary>
        internal static string tTitleQtyBillReturn {
            get {
                return ResourceManager.GetString("tTitleQtyBillReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนบิลขาย.
        /// </summary>
        internal static string tTitleQtyBillSale {
            get {
                return ResourceManager.GetString("tTitleQtyBillSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนบิลรวม.
        /// </summary>
        internal static string tTitleQtyBillTotal {
            get {
                return ResourceManager.GetString("tTitleQtyBillTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายการขาย.
        /// </summary>
        internal static string tTitleSaleData {
            get {
                return ResourceManager.GetString("tTitleSaleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 อันดับสินค้าขายดี ตามจำนวน.
        /// </summary>
        internal static string tTitleTopPdtQty {
            get {
                return ResourceManager.GetString("tTitleTopPdtQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 อันดับสินค้าขายดี ตามมูลค่า.
        /// </summary>
        internal static string tTitleTopPdtValue {
            get {
                return ResourceManager.GetString("tTitleTopPdtValue", resourceCulture);
            }
        }
    }
}
