//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaPos.Resources_String.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resHome_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resHome_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdaPos.Resources_String.Local.resHome_EN", typeof(resHome_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Top-up.
        /// </summary>
        internal static string tCancelTopup {
            get {
                return ResourceManager.GetString("tCancelTopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string tDashboard {
            get {
                return ResourceManager.GetString("tDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        internal static string tExpired {
            get {
                return ResourceManager.GetString("tExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Bill.
        /// </summary>
        internal static string tHold {
            get {
                return ResourceManager.GetString("tHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string tHome {
            get {
                return ResourceManager.GetString("tHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input Password.
        /// </summary>
        internal static string tInputPin {
            get {
                return ResourceManager.GetString("tInputPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.
        /// </summary>
        internal static string tMaster {
            get {
                return ResourceManager.GetString("tMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money In.
        /// </summary>
        internal static string tMnyIn {
            get {
                return ResourceManager.GetString("tMnyIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money Out.
        /// </summary>
        internal static string tMnyOut {
            get {
                return ResourceManager.GetString("tMnyOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open drawer. (No Sale).
        /// </summary>
        internal static string tOpnDrw {
            get {
                return ResourceManager.GetString("tOpnDrw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment summary by type.
        /// </summary>
        internal static string tPayment {
            get {
                return ResourceManager.GetString("tPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental.
        /// </summary>
        internal static string tRental {
            get {
                return ResourceManager.GetString("tRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Rental.
        /// </summary>
        internal static string tReturnRental {
            get {
                return ResourceManager.GetString("tReturnRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Sale.
        /// </summary>
        internal static string tReturnSale {
            get {
                return ResourceManager.GetString("tReturnSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale.
        /// </summary>
        internal static string tSale {
            get {
                return ResourceManager.GetString("tSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale summary.
        /// </summary>
        internal static string tSaleSum {
            get {
                return ResourceManager.GetString("tSaleSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string tSetting {
            get {
                return ResourceManager.GetString("tSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket.
        /// </summary>
        internal static string tTicket {
            get {
                return ResourceManager.GetString("tTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top-up.
        /// </summary>
        internal static string tTopup {
            get {
                return ResourceManager.GetString("tTopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void Bill.
        /// </summary>
        internal static string tVoid {
            get {
                return ResourceManager.GetString("tVoid", resourceCulture);
            }
        }
    }
}
