//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaPos.Resources_String.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resPriceCheck_TH {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resPriceCheck_TH() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdaPos.Resources_String.Local.resPriceCheck_TH", typeof(resPriceCheck_TH).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทุกหน่วย.
        /// </summary>
        internal static string tAllUnit {
            get {
                return ResourceManager.GetString("tAllUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ย้อนกลับ.
        /// </summary>
        internal static string tBack {
            get {
                return ResourceManager.GetString("tBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บาร์โค้ด.
        /// </summary>
        internal static string tBarcode {
            get {
                return ResourceManager.GetString("tBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตรวจสอบราคา.
        /// </summary>
        internal static string tBtnCheckPrice {
            get {
                return ResourceManager.GetString("tBtnCheckPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตรวจสอบโปรโมชั่น.
        /// </summary>
        internal static string tBtnCheckPromotion {
            get {
                return ResourceManager.GetString("tBtnCheckPromotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตรวจสอบราคา.
        /// </summary>
        internal static string tChkPrice {
            get {
                return ResourceManager.GetString("tChkPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสสินค้า.
        /// </summary>
        internal static string tCode {
            get {
                return ResourceManager.GetString("tCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขที่เอกสาร.
        /// </summary>
        internal static string tDocNo {
            get {
                return ResourceManager.GetString("tDocNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อัตราส่วน.
        /// </summary>
        internal static string tFactor {
            get {
                return ResourceManager.GetString("tFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่สิ้นสุด.
        /// </summary>
        internal static string tFinish {
            get {
                return ResourceManager.GetString("tFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คีย์บอร์ด.
        /// </summary>
        internal static string tKeyboard {
            get {
                return ResourceManager.GetString("tKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบสินค้าหรือบาร์โค้ดนี้.
        /// </summary>
        internal static string tMsgNotFound {
            get {
                return ResourceManager.GetString("tMsgNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อสินค้า.
        /// </summary>
        internal static string tName {
            get {
                return ResourceManager.GetString("tName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กลุ่มสินค้า.
        /// </summary>
        internal static string tPdtGrp {
            get {
                return ResourceManager.GetString("tPdtGrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ปรับเพิ่มมูลค่า.
        /// </summary>
        internal static string tPriAdjChgAmt {
            get {
                return ResourceManager.GetString("tPriAdjChgAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ปรับเพิ่ม %.
        /// </summary>
        internal static string tPriAdjChgPer {
            get {
                return ResourceManager.GetString("tPriAdjChgPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ปรับลดมูลค่า.
        /// </summary>
        internal static string tPriAdjDisAmt {
            get {
                return ResourceManager.GetString("tPriAdjDisAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ปรับลด %.
        /// </summary>
        internal static string tPriAdjDisPer {
            get {
                return ResourceManager.GetString("tPriAdjDisPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ราคาใหม่.
        /// </summary>
        internal static string tPriAdjNewPri {
            get {
                return ResourceManager.GetString("tPriAdjNewPri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ราคา.
        /// </summary>
        internal static string tPrice {
            get {
                return ResourceManager.GetString("tPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กลุ่มราคา.
        /// </summary>
        internal static string tPriceGgroup {
            get {
                return ResourceManager.GetString("tPriceGgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทการปรับ.
        /// </summary>
        internal static string tPriStaAdj {
            get {
                return ResourceManager.GetString("tPriStaAdj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ราคาปกติ.
        /// </summary>
        internal static string tPriType {
            get {
                return ResourceManager.GetString("tPriType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โปรโมชั่น.
        /// </summary>
        internal static string tPromotion {
            get {
                return ResourceManager.GetString("tPromotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สแกนบาร์โค้ด.
        /// </summary>
        internal static string tScanBar {
            get {
                return ResourceManager.GetString("tScanBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่เริ่ม.
        /// </summary>
        internal static string tStart {
            get {
                return ResourceManager.GetString("tStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สินค้าคงคลัง.
        /// </summary>
        internal static string tStkBal {
            get {
                return ResourceManager.GetString("tStkBal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เวลาที่สิ้นสุด.
        /// </summary>
        internal static string tTFinish {
            get {
                return ResourceManager.GetString("tTFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เวลาที่เริ่มต้น.
        /// </summary>
        internal static string tTStart {
            get {
                return ResourceManager.GetString("tTStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หน่วย.
        /// </summary>
        internal static string tUnit {
            get {
                return ResourceManager.GetString("tUnit", resourceCulture);
            }
        }
    }
}
