//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaPos.Resources_String.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resProduct_TH {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resProduct_TH() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdaPos.Resources_String.Local.resProduct_TH", typeof(resProduct_TH).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เคลื่อนไหว.
        /// </summary>
        internal static string tActive {
            get {
                return ResourceManager.GetString("tActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อายุสินค้า.
        /// </summary>
        internal static string tAge {
            get {
                return ResourceManager.GetString("tAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายปี.
        /// </summary>
        internal static string tAnnual {
            get {
                return ResourceManager.GetString("tAnnual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตัวเลข หรือ ตัวอักษร บอกถึงเนื้อผ้า.
        /// </summary>
        internal static string tArticle {
            get {
                return ResourceManager.GetString("tArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คงเหลือ.
        /// </summary>
        internal static string tBalance {
            get {
                return ResourceManager.GetString("tBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บาร์โค้ด.
        /// </summary>
        internal static string tBarcode {
            get {
                return ResourceManager.GetString("tBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยี่ห้อ.
        /// </summary>
        internal static string tBrand {
            get {
                return ResourceManager.GetString("tBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เปิดใช้งานคำนวน.
        /// </summary>
        internal static string tCal {
            get {
                return ResourceManager.GetString("tCal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string tClass {
            get {
                return ResourceManager.GetString("tClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัส.
        /// </summary>
        internal static string tCode {
            get {
                return ResourceManager.GetString("tCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สี.
        /// </summary>
        internal static string tColor {
            get {
                return ResourceManager.GetString("tColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สินค้าควบคุม.
        /// </summary>
        internal static string tControlSpc {
            get {
                return ResourceManager.GetString("tControlSpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ต้นทุนรวม.
        /// </summary>
        internal static string tCostAmt {
            get {
                return ResourceManager.GetString("tCostAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ราคาต้นทุนเฉลี่ย.
        /// </summary>
        internal static string tCostAvg {
            get {
                return ResourceManager.GetString("tCostAvg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ราคาต้นทุนกำหนดเอง.
        /// </summary>
        internal static string tCostDfn {
            get {
                return ResourceManager.GetString("tCostDfn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ราคาต้นทุนเข้าก่อนออกก่อน.
        /// </summary>
        internal static string tCostFiFo {
            get {
                return ResourceManager.GetString("tCostFiFo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ราคาต้นทุนซื้อครั้งสุดท้าย.
        /// </summary>
        internal static string tCostLst {
            get {
                return ResourceManager.GetString("tCostLst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ต้นทุนอื่น.
        /// </summary>
        internal static string tCostOth {
            get {
                return ResourceManager.GetString("tCostOth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ต้นทุนมาตรฐาน.
        /// </summary>
        internal static string tCostStd {
            get {
                return ResourceManager.GetString("tCostStd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ซื้อขาด.
        /// </summary>
        internal static string tCsm {
            get {
                return ResourceManager.GetString("tCsm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่กำหนดเอง.
        /// </summary>
        internal static string tCustomDay {
            get {
                return ResourceManager.GetString("tCustomDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายวัน.
        /// </summary>
        internal static string tDaily {
            get {
                return ResourceManager.GetString("tDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กลุ่มสินค้าตาม DCS.
        /// </summary>
        internal static string tDcs {
            get {
                return ResourceManager.GetString("tDcs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมวด.
        /// </summary>
        internal static string tDepart {
            get {
                return ResourceManager.GetString("tDepart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค่ามัดจำ.
        /// </summary>
        internal static string tDeposit {
            get {
                return ResourceManager.GetString("tDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อนุญาตลด / ชาร์จ.
        /// </summary>
        internal static string tDisChg {
            get {
                return ResourceManager.GetString("tDisChg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ช่วงเวลาห้ามขาย.
        /// </summary>
        internal static string tEvent {
            get {
                return ResourceManager.GetString("tEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อัตราส่วน.
        /// </summary>
        internal static string tFactor {
            get {
                return ResourceManager.GetString("tFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แฟชั่น.
        /// </summary>
        internal static string tFashion {
            get {
                return ResourceManager.GetString("tFashion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค่าเช่า.
        /// </summary>
        internal static string tFee {
            get {
                return ResourceManager.GetString("tFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สินค้าทั่วไป.
        /// </summary>
        internal static string tGeneral {
            get {
                return ResourceManager.GetString("tGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ของแถม.
        /// </summary>
        internal static string tGift {
            get {
                return ResourceManager.GetString("tGift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กลุ่ม.
        /// </summary>
        internal static string tGroup {
            get {
                return ResourceManager.GetString("tGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายชั่วโมง.
        /// </summary>
        internal static string tHourly {
            get {
                return ResourceManager.GetString("tHourly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลทั่วไป.
        /// </summary>
        internal static string tInformation {
            get {
                return ResourceManager.GetString("tInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระดับจำนวนสูงสุด.
        /// </summary>
        internal static string tMax {
            get {
                return ResourceManager.GetString("tMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อุณหภูมิ สูงสุด.
        /// </summary>
        internal static string tMaxHeart {
            get {
                return ResourceManager.GetString("tMaxHeart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่ผลิต.
        /// </summary>
        internal static string tMfg {
            get {
                return ResourceManager.GetString("tMfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระดับจำนวนต่ำสุด.
        /// </summary>
        internal static string tMin {
            get {
                return ResourceManager.GetString("tMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รุ่น.
        /// </summary>
        internal static string tModel {
            get {
                return ResourceManager.GetString("tModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายเดือน.
        /// </summary>
        internal static string tMonthly {
            get {
                return ResourceManager.GetString("tMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อ.
        /// </summary>
        internal static string tName {
            get {
                return ResourceManager.GetString("tName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อสินค้าอย่างย่อ (ABB).
        /// </summary>
        internal static string tNameABB {
            get {
                return ResourceManager.GetString("tNameABB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่ใช้งาน.
        /// </summary>
        internal static string tNotAllowAll {
            get {
                return ResourceManager.GetString("tNotAllowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ราคาขาย Online.
        /// </summary>
        internal static string tOlnPri {
            get {
                return ResourceManager.GetString("tOlnPri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แก้ไขได้.
        /// </summary>
        internal static string tOpenPLU {
            get {
                return ResourceManager.GetString("tOpenPLU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อื่นๆ.
        /// </summary>
        internal static string tOther {
            get {
                return ResourceManager.GetString("tOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่ออื่น.
        /// </summary>
        internal static string tOtherName {
            get {
                return ResourceManager.GetString("tOtherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อสินค้า เพิ่มเติม.
        /// </summary>
        internal static string tOthName {
            get {
                return ResourceManager.GetString("tOthName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พบ {0} แถว. หน้า {1}/{2}.
        /// </summary>
        internal static string tPage {
            get {
                return ResourceManager.GetString("tPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กลุ่มสินค้า.
        /// </summary>
        internal static string tPdtGrp {
            get {
                return ResourceManager.GetString("tPdtGrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทสินค้า.
        /// </summary>
        internal static string tPdtType {
            get {
                return ResourceManager.GetString("tPdtType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนแต้มสำหรับแลกสินค้า.
        /// </summary>
        internal static string tPntTime {
            get {
                return ResourceManager.GetString("tPntTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ให้แต้ม.
        /// </summary>
        internal static string tPoint {
            get {
                return ResourceManager.GetString("tPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ราคา.
        /// </summary>
        internal static string tPrice {
            get {
                return ResourceManager.GetString("tPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สินค้า.
        /// </summary>
        internal static string tProduct {
            get {
                return ResourceManager.GetString("tProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สินค้าปกติ.
        /// </summary>
        internal static string tProductN {
            get {
                return ResourceManager.GetString("tProductN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สินค้าปกติชุด.
        /// </summary>
        internal static string tProductSet {
            get {
                return ResourceManager.GetString("tProductSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนสั่งซื้อที่เหมาะสม.
        /// </summary>
        internal static string tQtyOrdBuy {
            get {
                return ResourceManager.GetString("tQtyOrdBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สินค้าอ้างอิงจากร้านค้า.
        /// </summary>
        internal static string tRefShop {
            get {
                return ResourceManager.GetString("tRefShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเหตุ.
        /// </summary>
        internal static string tRemark {
            get {
                return ResourceManager.GetString("tRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เช่า.
        /// </summary>
        internal static string tRental {
            get {
                return ResourceManager.GetString("tRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ราคาตามหน่วย.
        /// </summary>
        internal static string tRepack {
            get {
                return ResourceManager.GetString("tRepack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คืนสินค้า.
        /// </summary>
        internal static string tRequestReturn {
            get {
                return ResourceManager.GetString("tRequestReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ราคาขายปลีก.
        /// </summary>
        internal static string tRetpri {
            get {
                return ResourceManager.GetString("tRetpri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อนุญาตคืน.
        /// </summary>
        internal static string tReturn {
            get {
                return ResourceManager.GetString("tReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บังคับใช้.
        /// </summary>
        internal static string tSalePrice {
            get {
                return ResourceManager.GetString("tSalePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่เริ่มขาย.
        /// </summary>
        internal static string tSaleStart {
            get {
                return ResourceManager.GetString("tSaleStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่สิ้นสุดขาย.
        /// </summary>
        internal static string tSaleStop {
            get {
                return ResourceManager.GetString("tSaleStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใช้ราคาขาย.
        /// </summary>
        internal static string tSaleType {
            get {
                return ResourceManager.GetString("tSaleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to น้ำหนัก.
        /// </summary>
        internal static string tScales {
            get {
                return ResourceManager.GetString("tScales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค้นหา.
        /// </summary>
        internal static string tSearch {
            get {
                return ResourceManager.GetString("tSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ฤดูกาล.
        /// </summary>
        internal static string tSeason {
            get {
                return ResourceManager.GetString("tSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สินค้า Serial.
        /// </summary>
        internal static string tSerial {
            get {
                return ResourceManager.GetString("tSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สินค้า Serial Set.
        /// </summary>
        internal static string tSerialSet {
            get {
                return ResourceManager.GetString("tSerialSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สินค้าบริการ.
        /// </summary>
        internal static string tService {
            get {
                return ResourceManager.GetString("tService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สินค้าชุดหรือ Serial.
        /// </summary>
        internal static string tSetOrSN {
            get {
                return ResourceManager.GetString("tSetOrSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ราคาชุด.
        /// </summary>
        internal static string tSetPrice {
            get {
                return ResourceManager.GetString("tSetPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานะการใช้ราคา.
        /// </summary>
        internal static string tSetPriSta {
            get {
                return ResourceManager.GetString("tSetPriSta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แสดงรายการย่อย.
        /// </summary>
        internal static string tSetShwDt {
            get {
                return ResourceManager.GetString("tSetShwDt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ร้านค้า.
        /// </summary>
        internal static string tShop {
            get {
                return ResourceManager.GetString("tShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กดปุ่มค้นหาเพื่อโชว์ข้อมูล.
        /// </summary>
        internal static string tShowData {
            get {
                return ResourceManager.GetString("tShowData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขนาด.
        /// </summary>
        internal static string tSize {
            get {
                return ResourceManager.GetString("tSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สินค้าพิเศษ.
        /// </summary>
        internal static string tSpecial {
            get {
                return ResourceManager.GetString("tSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ราคาตามช่วง.
        /// </summary>
        internal static string tStepPrice {
            get {
                return ResourceManager.GetString("tStepPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ควบคุมสต๊อก.
        /// </summary>
        internal static string tStkCtl {
            get {
                return ResourceManager.GetString("tStkCtl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อัตราส่วนสต๊อก.
        /// </summary>
        internal static string tStkFac {
            get {
                return ResourceManager.GetString("tStkFac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Class.
        /// </summary>
        internal static string tSubClass {
            get {
                return ResourceManager.GetString("tSubClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ราคาย่อย.
        /// </summary>
        internal static string tSumPrice {
            get {
                return ResourceManager.GetString("tSumPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้จำหน่าย.
        /// </summary>
        internal static string tSupplier {
            get {
                return ResourceManager.GetString("tSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กลุ่มหน้าจอ Touch Screen.
        /// </summary>
        internal static string tTchGrp {
            get {
                return ResourceManager.GetString("tTchGrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระยะเวลาให้เช่า.
        /// </summary>
        internal static string tTime {
            get {
                return ResourceManager.GetString("tTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภท.
        /// </summary>
        internal static string tType {
            get {
                return ResourceManager.GetString("tType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หน่วย.
        /// </summary>
        internal static string tUnit {
            get {
                return ResourceManager.GetString("tUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่ระบุ.
        /// </summary>
        internal static string tUnknown {
            get {
                return ResourceManager.GetString("tUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ภาษี.
        /// </summary>
        internal static string tVat {
            get {
                return ResourceManager.GetString("tVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เครื่องชั่ง.
        /// </summary>
        internal static string tWeight {
            get {
                return ResourceManager.GetString("tWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ราคาขายส่ง.
        /// </summary>
        internal static string tWhsPri {
            get {
                return ResourceManager.GetString("tWhsPri", resourceCulture);
            }
        }
    }
}
