//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaPos.Resources_String.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resProduct_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resProduct_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdaPos.Resources_String.Local.resProduct_EN", typeof(resProduct_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string tActive {
            get {
                return ResourceManager.GetString("tActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age of product.
        /// </summary>
        internal static string tAge {
            get {
                return ResourceManager.GetString("tAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual.
        /// </summary>
        internal static string tAnnual {
            get {
                return ResourceManager.GetString("tAnnual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        internal static string tArticle {
            get {
                return ResourceManager.GetString("tArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string tBalance {
            get {
                return ResourceManager.GetString("tBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        internal static string tBarcode {
            get {
                return ResourceManager.GetString("tBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string tBrand {
            get {
                return ResourceManager.GetString("tBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Calculation.
        /// </summary>
        internal static string tCal {
            get {
                return ResourceManager.GetString("tCal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string tClass {
            get {
                return ResourceManager.GetString("tClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string tCode {
            get {
                return ResourceManager.GetString("tCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string tColor {
            get {
                return ResourceManager.GetString("tColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Special.
        /// </summary>
        internal static string tControlSpc {
            get {
                return ResourceManager.GetString("tControlSpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Amount.
        /// </summary>
        internal static string tCostAmt {
            get {
                return ResourceManager.GetString("tCostAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Average.
        /// </summary>
        internal static string tCostAvg {
            get {
                return ResourceManager.GetString("tCostAvg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Define.
        /// </summary>
        internal static string tCostDfn {
            get {
                return ResourceManager.GetString("tCostDfn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost FiFo.
        /// </summary>
        internal static string tCostFiFo {
            get {
                return ResourceManager.GetString("tCostFiFo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Last.
        /// </summary>
        internal static string tCostLst {
            get {
                return ResourceManager.GetString("tCostLst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Other.
        /// </summary>
        internal static string tCostOth {
            get {
                return ResourceManager.GetString("tCostOth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Standard.
        /// </summary>
        internal static string tCostStd {
            get {
                return ResourceManager.GetString("tCostStd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consignment.
        /// </summary>
        internal static string tCsm {
            get {
                return ResourceManager.GetString("tCsm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom (Day).
        /// </summary>
        internal static string tCustomDay {
            get {
                return ResourceManager.GetString("tCustomDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        internal static string tDaily {
            get {
                return ResourceManager.GetString("tDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCS.
        /// </summary>
        internal static string tDcs {
            get {
                return ResourceManager.GetString("tDcs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depart.
        /// </summary>
        internal static string tDepart {
            get {
                return ResourceManager.GetString("tDepart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        internal static string tDeposit {
            get {
                return ResourceManager.GetString("tDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount / Charge.
        /// </summary>
        internal static string tDisChg {
            get {
                return ResourceManager.GetString("tDisChg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time for Sale.
        /// </summary>
        internal static string tEvent {
            get {
                return ResourceManager.GetString("tEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor.
        /// </summary>
        internal static string tFactor {
            get {
                return ResourceManager.GetString("tFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fashion.
        /// </summary>
        internal static string tFashion {
            get {
                return ResourceManager.GetString("tFashion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee.
        /// </summary>
        internal static string tFee {
            get {
                return ResourceManager.GetString("tFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Product.
        /// </summary>
        internal static string tGeneral {
            get {
                return ResourceManager.GetString("tGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift.
        /// </summary>
        internal static string tGift {
            get {
                return ResourceManager.GetString("tGift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string tGroup {
            get {
                return ResourceManager.GetString("tGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly.
        /// </summary>
        internal static string tHourly {
            get {
                return ResourceManager.GetString("tHourly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string tInformation {
            get {
                return ResourceManager.GetString("tInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Maximum.
        /// </summary>
        internal static string tMax {
            get {
                return ResourceManager.GetString("tMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max heat of product.
        /// </summary>
        internal static string tMaxHeart {
            get {
                return ResourceManager.GetString("tMaxHeart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Manufacturing.
        /// </summary>
        internal static string tMfg {
            get {
                return ResourceManager.GetString("tMfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Minimum.
        /// </summary>
        internal static string tMin {
            get {
                return ResourceManager.GetString("tMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string tModel {
            get {
                return ResourceManager.GetString("tModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        internal static string tMonthly {
            get {
                return ResourceManager.GetString("tMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string tName {
            get {
                return ResourceManager.GetString("tName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (ABB).
        /// </summary>
        internal static string tNameABB {
            get {
                return ResourceManager.GetString("tNameABB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Allow All.
        /// </summary>
        internal static string tNotAllowAll {
            get {
                return ResourceManager.GetString("tNotAllowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Price.
        /// </summary>
        internal static string tOlnPri {
            get {
                return ResourceManager.GetString("tOlnPri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open PLU.
        /// </summary>
        internal static string tOpenPLU {
            get {
                return ResourceManager.GetString("tOpenPLU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Product.
        /// </summary>
        internal static string tOther {
            get {
                return ResourceManager.GetString("tOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Name.
        /// </summary>
        internal static string tOtherName {
            get {
                return ResourceManager.GetString("tOtherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Name.
        /// </summary>
        internal static string tOthName {
            get {
                return ResourceManager.GetString("tOthName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} records. Page {1}/{2}.
        /// </summary>
        internal static string tPage {
            get {
                return ResourceManager.GetString("tPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Group.
        /// </summary>
        internal static string tPdtGrp {
            get {
                return ResourceManager.GetString("tPdtGrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type.
        /// </summary>
        internal static string tPdtType {
            get {
                return ResourceManager.GetString("tPdtType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Time.
        /// </summary>
        internal static string tPntTime {
            get {
                return ResourceManager.GetString("tPntTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Giving.
        /// </summary>
        internal static string tPoint {
            get {
                return ResourceManager.GetString("tPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string tPrice {
            get {
                return ResourceManager.GetString("tPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string tProduct {
            get {
                return ResourceManager.GetString("tProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Product.
        /// </summary>
        internal static string tProductN {
            get {
                return ResourceManager.GetString("tProductN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Product.
        /// </summary>
        internal static string tProductSet {
            get {
                return ResourceManager.GetString("tProductSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty Order Buy.
        /// </summary>
        internal static string tQtyOrdBuy {
            get {
                return ResourceManager.GetString("tQtyOrdBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Shop.
        /// </summary>
        internal static string tRefShop {
            get {
                return ResourceManager.GetString("tRefShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        internal static string tRemark {
            get {
                return ResourceManager.GetString("tRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental.
        /// </summary>
        internal static string tRental {
            get {
                return ResourceManager.GetString("tRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repack.
        /// </summary>
        internal static string tRepack {
            get {
                return ResourceManager.GetString("tRepack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Return.
        /// </summary>
        internal static string tRequestReturn {
            get {
                return ResourceManager.GetString("tRequestReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail  Price.
        /// </summary>
        internal static string tRetpri {
            get {
                return ResourceManager.GetString("tRetpri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string tReturn {
            get {
                return ResourceManager.GetString("tReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Price.
        /// </summary>
        internal static string tSalePrice {
            get {
                return ResourceManager.GetString("tSalePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Start.
        /// </summary>
        internal static string tSaleStart {
            get {
                return ResourceManager.GetString("tSaleStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Stop.
        /// </summary>
        internal static string tSaleStop {
            get {
                return ResourceManager.GetString("tSaleStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Type.
        /// </summary>
        internal static string tSaleType {
            get {
                return ResourceManager.GetString("tSaleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scales.
        /// </summary>
        internal static string tScales {
            get {
                return ResourceManager.GetString("tScales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string tSearch {
            get {
                return ResourceManager.GetString("tSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season.
        /// </summary>
        internal static string tSeason {
            get {
                return ResourceManager.GetString("tSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Product.
        /// </summary>
        internal static string tSerial {
            get {
                return ResourceManager.GetString("tSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Set Product.
        /// </summary>
        internal static string tSerialSet {
            get {
                return ResourceManager.GetString("tSerialSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Product.
        /// </summary>
        internal static string tService {
            get {
                return ResourceManager.GetString("tService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set or Serial.
        /// </summary>
        internal static string tSetOrSN {
            get {
                return ResourceManager.GetString("tSetOrSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Price.
        /// </summary>
        internal static string tSetPrice {
            get {
                return ResourceManager.GetString("tSetPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Price Status.
        /// </summary>
        internal static string tSetPriSta {
            get {
                return ResourceManager.GetString("tSetPriSta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Show Detail.
        /// </summary>
        internal static string tSetShwDt {
            get {
                return ResourceManager.GetString("tSetShwDt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        internal static string tShop {
            get {
                return ResourceManager.GetString("tShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press button search for show data.
        /// </summary>
        internal static string tShowData {
            get {
                return ResourceManager.GetString("tShowData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string tSize {
            get {
                return ResourceManager.GetString("tSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Product.
        /// </summary>
        internal static string tSpecial {
            get {
                return ResourceManager.GetString("tSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Price.
        /// </summary>
        internal static string tStepPrice {
            get {
                return ResourceManager.GetString("tStepPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Control.
        /// </summary>
        internal static string tStkCtl {
            get {
                return ResourceManager.GetString("tStkCtl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Factor.
        /// </summary>
        internal static string tStkFac {
            get {
                return ResourceManager.GetString("tStkFac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Class.
        /// </summary>
        internal static string tSubClass {
            get {
                return ResourceManager.GetString("tSubClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary Price.
        /// </summary>
        internal static string tSumPrice {
            get {
                return ResourceManager.GetString("tSumPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        internal static string tSupplier {
            get {
                return ResourceManager.GetString("tSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch Screen Group.
        /// </summary>
        internal static string tTchGrp {
            get {
                return ResourceManager.GetString("tTchGrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty time.
        /// </summary>
        internal static string tTime {
            get {
                return ResourceManager.GetString("tTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string tType {
            get {
                return ResourceManager.GetString("tType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string tUnit {
            get {
                return ResourceManager.GetString("tUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string tUnknown {
            get {
                return ResourceManager.GetString("tUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vat.
        /// </summary>
        internal static string tVat {
            get {
                return ResourceManager.GetString("tVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string tWeight {
            get {
                return ResourceManager.GetString("tWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wholesale Price.
        /// </summary>
        internal static string tWhsPri {
            get {
                return ResourceManager.GetString("tWhsPri", resourceCulture);
            }
        }
    }
}
