//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaPos.Resources_String.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resRegister_TH {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resRegister_TH() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdaPos.Resources_String.Local.resRegister_TH", typeof(resRegister_TH).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ฉันยอมรับ.
        /// </summary>
        internal static string tAccept {
            get {
                return ResourceManager.GetString("tAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการลงทะเบียน.
        /// </summary>
        internal static string tAcceptRegister {
            get {
                return ResourceManager.GetString("tAcceptRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันจุดขายไม่สำเร็จ.
        /// </summary>
        internal static string tActFail {
            get {
                return ResourceManager.GetString("tActFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันจุดขาย.
        /// </summary>
        internal static string tActivate {
            get {
                return ResourceManager.GetString("tActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันจุดขายสำเร็จ.
        /// </summary>
        internal static string tActSuccess {
            get {
                return ResourceManager.GetString("tActSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มีบัญชีร้านค้าแล้ว.
        /// </summary>
        internal static string tAlreadyAccount {
            get {
                return ResourceManager.GetString("tAlreadyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to และ.
        /// </summary>
        internal static string tAnd {
            get {
                return ResourceManager.GetString("tAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สาขา.
        /// </summary>
        internal static string tBch {
            get {
                return ResourceManager.GetString("tBch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนสาขา.
        /// </summary>
        internal static string tBchQty {
            get {
                return ResourceManager.GetString("tBchQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทธุรกิจ.
        /// </summary>
        internal static string tBsnType {
            get {
                return ResourceManager.GetString("tBsnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อร้านค้า / ชื่อลูกค้า.
        /// </summary>
        internal static string tBusinessName {
            get {
                return ResourceManager.GetString("tBusinessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แผนการใช้งาน.
        /// </summary>
        internal static string tBusinessType {
            get {
                return ResourceManager.GetString("tBusinessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากดยอมรับเงื่อนไขการให้บริการและนโยบายความเป็นส่วนตัว.
        /// </summary>
        internal static string tChkPrivacy {
            get {
                return ResourceManager.GetString("tChkPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คัดลอกเลขเครื่องจุดขาย.
        /// </summary>
        internal static string tCopyUUID {
            get {
                return ResourceManager.GetString("tCopyUUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลร้านค้า.
        /// </summary>
        internal static string tDataStore {
            get {
                return ResourceManager.GetString("tDataStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลวันหมดอายุ.
        /// </summary>
        internal static string tDateExpir {
            get {
                return ResourceManager.GetString("tDateExpir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทดลองใช้งาน.
        /// </summary>
        internal static string tDemo {
            get {
                return ResourceManager.GetString("tDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายละเอียด.
        /// </summary>
        internal static string tDetail {
            get {
                return ResourceManager.GetString("tDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อีเมล.
        /// </summary>
        internal static string tEmail {
            get {
                return ResourceManager.GetString("tEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รูปแบบอีเมลไม่ถูกต้อง.
        /// </summary>
        internal static string tEmailFormat {
            get {
                return ResourceManager.GetString("tEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่สิ้นสุด.
        /// </summary>
        internal static string tEndDate {
            get {
                return ResourceManager.GetString("tEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นำเข้าทะเบียนจุดขาย.
        /// </summary>
        internal static string tImpLic {
            get {
                return ResourceManager.GetString("tImpLic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * กรณีเครื่องจุดขายหมดอายุกรุณาติดต่อเจ้าหน้าที่.
        /// </summary>
        internal static string tLabelExp {
            get {
                return ResourceManager.GetString("tLabelExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บริษัทขอสงวนสิทธิ์ในการเปลี่ยนแปลงเงื่อนไขโดยไม่ต้องแจ้งให้ทราบล่วงหน้า.
        /// </summary>
        internal static string tLabelReg {
            get {
                return ResourceManager.GetString("tLabelReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกประเภทธุรกิจแค่ 1 รายการ.
        /// </summary>
        internal static string tMsgBsnTypeQty {
            get {
                return ResourceManager.GetString("tMsgBsnTypeQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คัดลอกเลขเครื่องจุดขายแล้ว.
        /// </summary>
        internal static string tMsgCopyUUID {
            get {
                return ResourceManager.GetString("tMsgCopyUUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบข้อมูล.
        /// </summary>
        internal static string tMsgDataNotFound {
            get {
                return ResourceManager.GetString("tMsgDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไฟล์ License ไม่ถูกต้อง.
        /// </summary>
        internal static string tMsgInvalidFileLic {
            get {
                return ResourceManager.GetString("tMsgInvalidFileLic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาอ่าน.
        /// </summary>
        internal static string tMsgRead {
            get {
                return ResourceManager.GetString("tMsgRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เบอร์โทรศัพท์ต้องมีความยาวอย่างน้อย 8 ตัว หรือมากกว่า.
        /// </summary>
        internal static string tMsgTelLength {
            get {
                return ResourceManager.GetString("tMsgTelLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลงทะเบียนใหม่.
        /// </summary>
        internal static string tNewAccount {
            get {
                return ResourceManager.GetString("tNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยังไม่ได้ระบุ.
        /// </summary>
        internal static string tNone {
            get {
                return ResourceManager.GetString("tNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อื่นๆ โปรดระบุ.
        /// </summary>
        internal static string tOther {
            get {
                return ResourceManager.GetString("tOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทแพ็คเกจ.
        /// </summary>
        internal static string tPackageType {
            get {
                return ResourceManager.GetString("tPackageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นโยบายความเป็นส่วนตัว.
        /// </summary>
        internal static string tPrivacy {
            get {
                return ResourceManager.GetString("tPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เปิดบัญชีร้านค้า.
        /// </summary>
        internal static string tRealStore {
            get {
                return ResourceManager.GetString("tRealStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสอ้างอิงลูกค้า.
        /// </summary>
        internal static string tRefCode {
            get {
                return ResourceManager.GetString("tRefCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เบอร์โทรศัพท์มีการใช้งานอยู่ในระบบแล้ว ระบบทำการส่งข้อมูลไปที่อีเมล กรุณาตรวจสอบอีเมล.
        /// </summary>
        internal static string tRegDuplicate {
            get {
                return ResourceManager.GetString("tRegDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลงทะเบียนไม่สำเร็จ.
        /// </summary>
        internal static string tRegError {
            get {
                return ResourceManager.GetString("tRegError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลงทะเบียนการใช้งาน.
        /// </summary>
        internal static string tRegister {
            get {
                return ResourceManager.GetString("tRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลการลงทะเบียน.
        /// </summary>
        internal static string tRegisterData {
            get {
                return ResourceManager.GetString("tRegisterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลงทะเบียนแล้ว.
        /// </summary>
        internal static string tRegistered {
            get {
                return ResourceManager.GetString("tRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลงทะเบียนใช้งานสำเร็จ, กรุณาตรวจสอบ บัญชีผู้ใช้งาน และรหัสผ่าน จากบัญชีอีเมลที่สมัคร.
        /// </summary>
        internal static string tRegSuccess {
            get {
                return ResourceManager.GetString("tRegSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่เริ่มต้น.
        /// </summary>
        internal static string tStartDate {
            get {
                return ResourceManager.GetString("tStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานะ.
        /// </summary>
        internal static string tStatus {
            get {
                return ResourceManager.GetString("tStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เครื่องจุดขายหมดอายุการใช้งาน.
        /// </summary>
        internal static string tStatusExp {
            get {
                return ResourceManager.GetString("tStatusExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เครื่องจุดขายใช้งานได้ปกติ.
        /// </summary>
        internal static string tStatusNotExp {
            get {
                return ResourceManager.GetString("tStatusNotExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เบอร์โทรศัพท์.
        /// </summary>
        internal static string tTel {
            get {
                return ResourceManager.GetString("tTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เงื่อนไขการให้บริการ.
        /// </summary>
        internal static string tTerms {
            get {
                return ResourceManager.GetString("tTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * กรุณาตรวจสอบนโยบายความเป็นส่วนตัว.
        /// </summary>
        internal static string tTitPrivicy {
            get {
                return ResourceManager.GetString("tTitPrivicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * กรุณาตรวจสอบเงื่อนไขการให้บริการ.
        /// </summary>
        internal static string tTitTerms {
            get {
                return ResourceManager.GetString("tTitTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขเครื่องจุดขาย.
        /// </summary>
        internal static string tUUID {
            get {
                return ResourceManager.GetString("tUUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาระบุ.
        /// </summary>
        internal static string tValidate {
            get {
                return ResourceManager.GetString("tValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตรวจสอบ.
        /// </summary>
        internal static string tVerify {
            get {
                return ResourceManager.GetString("tVerify", resourceCulture);
            }
        }
    }
}
