//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaPos.Resources_String.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resReturnCard_TH {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resReturnCard_TH() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdaPos.Resources_String.Local.resReturnCard_TH", typeof(resReturnCard_TH).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มูลค่าที่ใช้ได้.
        /// </summary>
        internal static string tAvailable {
            get {
                return ResourceManager.GetString("tAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยกเลิกเติมเงิน.
        /// </summary>
        internal static string tCancel {
            get {
                return ResourceManager.GetString("tCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนเงินยกเลิก.
        /// </summary>
        internal static string tCancelAmt {
            get {
                return ResourceManager.GetString("tCancelAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยกเลิก.
        /// </summary>
        internal static string tCmdCancel {
            get {
                return ResourceManager.GetString("tCmdCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยื่นยัน.
        /// </summary>
        internal static string tCmdConfirm {
            get {
                return ResourceManager.GetString("tCmdConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่.
        /// </summary>
        internal static string tCmdNo {
            get {
                return ResourceManager.GetString("tCmdNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มัดจำ.
        /// </summary>
        internal static string tDeposit {
            get {
                return ResourceManager.GetString("tDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันหมดอายุ.
        /// </summary>
        internal static string tExp {
            get {
                return ResourceManager.GetString("tExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถทำรายการได้ เนื่องจากบัตรยกเลิก.
        /// </summary>
        internal static string tMsgCrdCancel {
            get {
                return ResourceManager.GetString("tMsgCrdCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถทำรายการได้ เนื่องจากบัตรหมดอายุ.
        /// </summary>
        internal static string tMsgCrdExp {
            get {
                return ResourceManager.GetString("tMsgCrdExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถทำรายการได้ เนื่องจากบัตรไม่เคลื่อนไหว.
        /// </summary>
        internal static string tMsgCrdInactive {
            get {
                return ResourceManager.GetString("tMsgCrdInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอดเงินในบัตรหมดอายุ
        ///กรุณากด OK เพื่อเคลียร์ยอดเงินในบัตร และเติมเงิน
        ///หรือ กด Cancel เพื่อยกเลิกการเติมเงิน.
        /// </summary>
        internal static string tMsgCrdValueExp {
            get {
                return ResourceManager.GetString("tMsgCrdValueExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อริสแบนด์ / บัตร.
        /// </summary>
        internal static string tName {
            get {
                return ResourceManager.GetString("tName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเลขริสแบนด์ / บัตร.
        /// </summary>
        internal static string tNo {
            get {
                return ResourceManager.GetString("tNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชำระเงิน.
        /// </summary>
        internal static string tPayment {
            get {
                return ResourceManager.GetString("tPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เงินมัดจำสินค้า.
        /// </summary>
        internal static string tPdtDeposit {
            get {
                return ResourceManager.GetString("tPdtDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เงินด่วน.
        /// </summary>
        internal static string tQuick {
            get {
                return ResourceManager.GetString("tQuick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รับเงิน.
        /// </summary>
        internal static string tReceived {
            get {
                return ResourceManager.GetString("tReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คืนริสแบนด์ / บัตร.
        /// </summary>
        internal static string tReturnCard {
            get {
                return ResourceManager.GetString("tReturnCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มูลค่าริสแบนด์ / บัตร.
        /// </summary>
        internal static string tValue {
            get {
                return ResourceManager.GetString("tValue", resourceCulture);
            }
        }
    }
}
