//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaPos.Resources_String.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resRegister_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resRegister_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdaPos.Resources_String.Local.resRegister_EN", typeof(resRegister_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I accept.
        /// </summary>
        internal static string tAccept {
            get {
                return ResourceManager.GetString("tAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Register.
        /// </summary>
        internal static string tAcceptRegister {
            get {
                return ResourceManager.GetString("tAcceptRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Fail.
        /// </summary>
        internal static string tActFail {
            get {
                return ResourceManager.GetString("tActFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string tActivate {
            get {
                return ResourceManager.GetString("tActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Success.
        /// </summary>
        internal static string tActSuccess {
            get {
                return ResourceManager.GetString("tActSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account.
        /// </summary>
        internal static string tAlreadyAccount {
            get {
                return ResourceManager.GetString("tAlreadyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string tAnd {
            get {
                return ResourceManager.GetString("tAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        internal static string tBch {
            get {
                return ResourceManager.GetString("tBch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch quantity.
        /// </summary>
        internal static string tBchQty {
            get {
                return ResourceManager.GetString("tBchQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business type.
        /// </summary>
        internal static string tBsnType {
            get {
                return ResourceManager.GetString("tBsnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store / Customer name.
        /// </summary>
        internal static string tBusinessName {
            get {
                return ResourceManager.GetString("tBusinessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage plan.
        /// </summary>
        internal static string tBusinessType {
            get {
                return ResourceManager.GetString("tBusinessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please accept the terms of service and privacy policy..
        /// </summary>
        internal static string tChkPrivacy {
            get {
                return ResourceManager.GetString("tChkPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Pos ID.
        /// </summary>
        internal static string tCopyUUID {
            get {
                return ResourceManager.GetString("tCopyUUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Infomation.
        /// </summary>
        internal static string tDataStore {
            get {
                return ResourceManager.GetString("tDataStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration date information.
        /// </summary>
        internal static string tDateExpir {
            get {
                return ResourceManager.GetString("tDateExpir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo.
        /// </summary>
        internal static string tDemo {
            get {
                return ResourceManager.GetString("tDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string tDetail {
            get {
                return ResourceManager.GetString("tDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string tEmail {
            get {
                return ResourceManager.GetString("tEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date end.
        /// </summary>
        internal static string tEndDate {
            get {
                return ResourceManager.GetString("tEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import License.
        /// </summary>
        internal static string tImpLic {
            get {
                return ResourceManager.GetString("tImpLic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * In case of expired point of sale machines, please contact staff..
        /// </summary>
        internal static string tLabelExp {
            get {
                return ResourceManager.GetString("tLabelExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adasoft reserves the right to modify, at Adasoft&apos;s discretion, all or part of the Services as Adasoft determines necessary anytime without any prior notice to Users..
        /// </summary>
        internal static string tLabelReg {
            get {
                return ResourceManager.GetString("tLabelReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        internal static string tMsgBsnTypeQty {
            get {
                return ResourceManager.GetString("tMsgBsnTypeQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pos ID Copied..
        /// </summary>
        internal static string tMsgCopyUUID {
            get {
                return ResourceManager.GetString("tMsgCopyUUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License filed is invalid..
        /// </summary>
        internal static string tMsgInvalidFileLic {
            get {
                return ResourceManager.GetString("tMsgInvalidFileLic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please read .
        /// </summary>
        internal static string tMsgRead {
            get {
                return ResourceManager.GetString("tMsgRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone numbers must be at least 8 characters long or more..
        /// </summary>
        internal static string tMsgTelLength {
            get {
                return ResourceManager.GetString("tMsgTelLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Account.
        /// </summary>
        internal static string tNewAccount {
            get {
                return ResourceManager.GetString("tNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string tNone {
            get {
                return ResourceManager.GetString("tNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string tOther {
            get {
                return ResourceManager.GetString("tOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package type.
        /// </summary>
        internal static string tPackageType {
            get {
                return ResourceManager.GetString("tPackageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        internal static string tPrivacy {
            get {
                return ResourceManager.GetString("tPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Store Account.
        /// </summary>
        internal static string tRealStore {
            get {
                return ResourceManager.GetString("tRealStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref. Code..
        /// </summary>
        internal static string tRefCode {
            get {
                return ResourceManager.GetString("tRefCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone numbers is active in the system. The system will send information to Email, please check Email..
        /// </summary>
        internal static string tRegDuplicate {
            get {
                return ResourceManager.GetString("tRegDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Error.
        /// </summary>
        internal static string tRegError {
            get {
                return ResourceManager.GetString("tRegError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string tRegister {
            get {
                return ResourceManager.GetString("tRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration information.
        /// </summary>
        internal static string tRegisterData {
            get {
                return ResourceManager.GetString("tRegisterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered.
        /// </summary>
        internal static string tRegistered {
            get {
                return ResourceManager.GetString("tRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully registered, Please check the user account and password from your  mail account..
        /// </summary>
        internal static string tRegSuccess {
            get {
                return ResourceManager.GetString("tRegSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date start.
        /// </summary>
        internal static string tStartDate {
            get {
                return ResourceManager.GetString("tStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string tStatus {
            get {
                return ResourceManager.GetString("tStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The point of sale has expired..
        /// </summary>
        internal static string tStatusExp {
            get {
                return ResourceManager.GetString("tStatusExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The point of sale machine works normally..
        /// </summary>
        internal static string tStatusNotExp {
            get {
                return ResourceManager.GetString("tStatusNotExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel..
        /// </summary>
        internal static string tTel {
            get {
                return ResourceManager.GetString("tTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Service.
        /// </summary>
        internal static string tTerms {
            get {
                return ResourceManager.GetString("tTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please check the privacy policy..
        /// </summary>
        internal static string tTitPrivicy {
            get {
                return ResourceManager.GetString("tTitPrivicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please check the terms of service..
        /// </summary>
        internal static string tTitTerms {
            get {
                return ResourceManager.GetString("tTitTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pos ID.
        /// </summary>
        internal static string tUUID {
            get {
                return ResourceManager.GetString("tUUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify.
        /// </summary>
        internal static string tValidate {
            get {
                return ResourceManager.GetString("tValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        internal static string tVerify {
            get {
                return ResourceManager.GetString("tVerify", resourceCulture);
            }
        }
    }
}
