//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaPos.Resources_String.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resReprint_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resReprint_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdaPos.Resources_String.Local.resReprint_EN", typeof(resReprint_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string tAll {
            get {
                return ResourceManager.GetString("tAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string tAmount {
            get {
                return ResourceManager.GetString("tAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Type.
        /// </summary>
        internal static string tBillType {
            get {
                return ResourceManager.GetString("tBillType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string tClear {
            get {
                return ResourceManager.GetString("tClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time.
        /// </summary>
        internal static string tDatetime {
            get {
                return ResourceManager.GetString("tDatetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document No..
        /// </summary>
        internal static string tDocNo {
            get {
                return ResourceManager.GetString("tDocNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprint.
        /// </summary>
        internal static string tReprint {
            get {
                return ResourceManager.GetString("tReprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string tReturn {
            get {
                return ResourceManager.GetString("tReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale.
        /// </summary>
        internal static string tSale {
            get {
                return ResourceManager.GetString("tSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Date.
        /// </summary>
        internal static string tSaleDate {
            get {
                return ResourceManager.GetString("tSaleDate", resourceCulture);
            }
        }
    }
}
