//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaPos.Resources_String.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resReprint_TH {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resReprint_TH() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdaPos.Resources_String.Local.resReprint_TH", typeof(resReprint_TH).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทั้งหมด.
        /// </summary>
        internal static string tAll {
            get {
                return ResourceManager.GetString("tAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนเงิน.
        /// </summary>
        internal static string tAmount {
            get {
                return ResourceManager.GetString("tAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทของบิล.
        /// </summary>
        internal static string tBillType {
            get {
                return ResourceManager.GetString("tBillType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เคลียร์.
        /// </summary>
        internal static string tClear {
            get {
                return ResourceManager.GetString("tClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันและเวลา.
        /// </summary>
        internal static string tDatetime {
            get {
                return ResourceManager.GetString("tDatetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเลขเอกสาร.
        /// </summary>
        internal static string tDocNo {
            get {
                return ResourceManager.GetString("tDocNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พิมพ์ซ้ำ.
        /// </summary>
        internal static string tReprint {
            get {
                return ResourceManager.GetString("tReprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การคืน.
        /// </summary>
        internal static string tReturn {
            get {
                return ResourceManager.GetString("tReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การขาย.
        /// </summary>
        internal static string tSale {
            get {
                return ResourceManager.GetString("tSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่ขาย.
        /// </summary>
        internal static string tSaleDate {
            get {
                return ResourceManager.GetString("tSaleDate", resourceCulture);
            }
        }
    }
}
