//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaPos.Resources_String.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resSync_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resSync_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdaPos.Resources_String.Local.resSync_EN", typeof(resSync_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add product unsuccess..
        /// </summary>
        internal static string tAddPdtUnSuccess {
            get {
                return ResourceManager.GetString("tAddPdtUnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Promotion.
        /// </summary>
        internal static string tCalPmt {
            get {
                return ResourceManager.GetString("tCalPmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date compare.
        /// </summary>
        internal static string tDateCompare {
            get {
                return ResourceManager.GetString("tDateCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string tDownload {
            get {
                return ResourceManager.GetString("tDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Bill.
        /// </summary>
        internal static string tExportBill {
            get {
                return ResourceManager.GetString("tExportBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Bill Error.
        /// </summary>
        internal static string tExportBillError {
            get {
                return ResourceManager.GetString("tExportBillError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Bill Success.
        /// </summary>
        internal static string tExportBillSuccess {
            get {
                return ResourceManager.GetString("tExportBillSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Date.
        /// </summary>
        internal static string tLastDate {
            get {
                return ResourceManager.GetString("tLastDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        internal static string tMsgTimeout {
            get {
                return ResourceManager.GetString("tMsgTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed, sales cannot be sent to headquarters !!!.
        /// </summary>
        internal static string tMsgUldConnError {
            get {
                return ResourceManager.GetString("tMsgUldConnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system is sending sales data to the headquarters system. Please wait ....
        /// </summary>
        internal static string tMsgUldConnSucc {
            get {
                return ResourceManager.GetString("tMsgUldConnSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare User Data.
        /// </summary>
        internal static string tPrgsTxt_0 {
            get {
                return ResourceManager.GetString("tPrgsTxt_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Fix Doc Data.
        /// </summary>
        internal static string tPrgsTxt_10 {
            get {
                return ResourceManager.GetString("tPrgsTxt_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare Product price.
        /// </summary>
        internal static string tPrgsTxt_20 {
            get {
                return ResourceManager.GetString("tPrgsTxt_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare Product Data.
        /// </summary>
        internal static string tPrgsTxt_30 {
            get {
                return ResourceManager.GetString("tPrgsTxt_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare Promotion.
        /// </summary>
        internal static string tPrgsTxt_40 {
            get {
                return ResourceManager.GetString("tPrgsTxt_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare Pos.
        /// </summary>
        internal static string tPrgsTxt_5 {
            get {
                return ResourceManager.GetString("tPrgsTxt_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare Slip Data.
        /// </summary>
        internal static string tPrgsTxt_50 {
            get {
                return ResourceManager.GetString("tPrgsTxt_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Database.
        /// </summary>
        internal static string tPrgsTxt_60 {
            get {
                return ResourceManager.GetString("tPrgsTxt_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare Redeem Data.
        /// </summary>
        internal static string tPrgsTxt_70 {
            get {
                return ResourceManager.GetString("tPrgsTxt_70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare Coupon Data.
        /// </summary>
        internal static string tPrgsTxt_80 {
            get {
                return ResourceManager.GetString("tPrgsTxt_80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare Sale System.
        /// </summary>
        internal static string tPrgsTxt_90 {
            get {
                return ResourceManager.GetString("tPrgsTxt_90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check from last sync.
        /// </summary>
        internal static string tRecentUpdate {
            get {
                return ResourceManager.GetString("tRecentUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string tSearch {
            get {
                return ResourceManager.GetString("tSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string tSelectAll {
            get {
                return ResourceManager.GetString("tSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Pos.
        /// </summary>
        internal static string tSetupPos {
            get {
                return ResourceManager.GetString("tSetupPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Now.
        /// </summary>
        internal static string tShiftNow {
            get {
                return ResourceManager.GetString("tShiftNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status : Get Check Docs to HQ.
        /// </summary>
        internal static string tStaGetFixDoc {
            get {
                return ResourceManager.GetString("tStaGetFixDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status : All documents sale have been uploaded..
        /// </summary>
        internal static string tStaNoDocUploadSale {
            get {
                return ResourceManager.GetString("tStaNoDocUploadSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status : All documents Shif have been uploaded..
        /// </summary>
        internal static string tStaNoDocUploadShift {
            get {
                return ResourceManager.GetString("tStaNoDocUploadShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status : All documents Void DT have been uploaded..
        /// </summary>
        internal static string tStaNoDocUploadVoid {
            get {
                return ResourceManager.GetString("tStaNoDocUploadVoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string tStatus {
            get {
                return ResourceManager.GetString("tStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status : Upload Check Docs to HQ.
        /// </summary>
        internal static string tStaUploadFixDoc {
            get {
                return ResourceManager.GetString("tStaUploadFixDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status : Upload Sale-Refund.
        /// </summary>
        internal static string tStaUploadSale {
            get {
                return ResourceManager.GetString("tStaUploadSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status : Upload Shift.
        /// </summary>
        internal static string tStaUploadShift {
            get {
                return ResourceManager.GetString("tStaUploadShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status : Upload Void DT.
        /// </summary>
        internal static string tStaUploadVoid {
            get {
                return ResourceManager.GetString("tStaUploadVoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string tSuccess {
            get {
                return ResourceManager.GetString("tSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Download Error.
        /// </summary>
        internal static string tSycDwnError {
            get {
                return ResourceManager.GetString("tSycDwnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Download Success.
        /// </summary>
        internal static string tSycDwnSuccess {
            get {
                return ResourceManager.GetString("tSycDwnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete old data.
        /// </summary>
        internal static string tSyncDelAll {
            get {
                return ResourceManager.GetString("tSyncDelAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for Update Data.
        /// </summary>
        internal static string tTitleAutoSync {
            get {
                return ResourceManager.GetString("tTitleAutoSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates.
        /// </summary>
        internal static string tTitleChkUpd {
            get {
                return ResourceManager.GetString("tTitleChkUpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial the System.
        /// </summary>
        internal static string tTitleInitSys {
            get {
                return ResourceManager.GetString("tTitleInitSys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend Document.
        /// </summary>
        internal static string tTitleItemFixDoc {
            get {
                return ResourceManager.GetString("tTitleItemFixDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last date.
        /// </summary>
        internal static string tTitleLastDateDwn {
            get {
                return ResourceManager.GetString("tTitleLastDateDwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last date.
        /// </summary>
        internal static string tTitleLastDateUpl {
            get {
                return ResourceManager.GetString("tTitleLastDateUpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Name.
        /// </summary>
        internal static string tTitleNameDwn {
            get {
                return ResourceManager.GetString("tTitleNameDwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document No..
        /// </summary>
        internal static string tTitleNameUpl {
            get {
                return ResourceManager.GetString("tTitleNameUpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting up.
        /// </summary>
        internal static string tTitleSetupPos {
            get {
                return ResourceManager.GetString("tTitleSetupPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Upload ?.
        /// </summary>
        internal static string tTitleStopUpdSale {
            get {
                return ResourceManager.GetString("tTitleStopUpdSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string tType {
            get {
                return ResourceManager.GetString("tType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccess.
        /// </summary>
        internal static string tUnSuccess {
            get {
                return ResourceManager.GetString("tUnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string tUpload {
            get {
                return ResourceManager.GetString("tUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Data After Close shift.
        /// </summary>
        internal static string tUploadCloseShf {
            get {
                return ResourceManager.GetString("tUploadCloseShf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending product information to system. Please wait....
        /// </summary>
        internal static string tUploadPdt {
            get {
                return ResourceManager.GetString("tUploadPdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send product information to the system sucess..
        /// </summary>
        internal static string tUploadPdtSuccess {
            get {
                return ResourceManager.GetString("tUploadPdtSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send product information to the system unsucess..
        /// </summary>
        internal static string tUploadPdtUnSuccess {
            get {
                return ResourceManager.GetString("tUploadPdtUnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Success.
        /// </summary>
        internal static string tUploadSuccess {
            get {
                return ResourceManager.GetString("tUploadSuccess", resourceCulture);
            }
        }
    }
}
