//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaPos.Resources_String.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resSpotCheck_TH {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resSpotCheck_TH() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdaPos.Resources_String.Local.resSpotCheck_TH", typeof(resSpotCheck_TH).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เคลื่อนไหว.
        /// </summary>
        internal static string tActive {
            get {
                return ResourceManager.GetString("tActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มูลค่าที่ใช้ได้.
        /// </summary>
        internal static string tAvailable {
            get {
                return ResourceManager.GetString("tAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยกเลิก.
        /// </summary>
        internal static string tCancel {
            get {
                return ResourceManager.GetString("tCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานะบัตร.
        /// </summary>
        internal static string tCrdSta {
            get {
                return ResourceManager.GetString("tCrdSta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค่ามัดจำ ริสแบนด์ / บัตร.
        /// </summary>
        internal static string tDeposit {
            get {
                return ResourceManager.GetString("tDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันหมดอายุ.
        /// </summary>
        internal static string tExp {
            get {
                return ResourceManager.GetString("tExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เช็คยอดบัตร / ริชแบนด์.
        /// </summary>
        internal static string tHistory {
            get {
                return ResourceManager.GetString("tHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อริสแบนด์ / บัตร.
        /// </summary>
        internal static string tName {
            get {
                return ResourceManager.GetString("tName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่เคลื่อนไหว.
        /// </summary>
        internal static string tNoActive {
            get {
                return ResourceManager.GetString("tNoActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค่ามัดจำสินค้า.
        /// </summary>
        internal static string tPdtDepo {
            get {
                return ResourceManager.GetString("tPdtDepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เช็คยอดริสแบนด์ / บัตร.
        /// </summary>
        internal static string tSpotCheck {
            get {
                return ResourceManager.GetString("tSpotCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทริสแบนด์ / บัตร.
        /// </summary>
        internal static string tType {
            get {
                return ResourceManager.GetString("tType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มูลค่าริสแบนด์ / บัตร.
        /// </summary>
        internal static string tValue {
            get {
                return ResourceManager.GetString("tValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเลขริสแบนด์ / บัตร.
        /// </summary>
        internal static string tWBNo {
            get {
                return ResourceManager.GetString("tWBNo", resourceCulture);
            }
        }
    }
}
