//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaPos.Resources_String.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resSale_TH {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resSale_TH() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdaPos.Resources_String.Local.resSale_TH", typeof(resSale_TH).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทั้งหมด.
        /// </summary>
        internal static string tAll {
            get {
                return ResourceManager.GetString("tAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เปลี่ยนจำนวน.
        /// </summary>
        internal static string tChgQty {
            get {
                return ResourceManager.GetString("tChgQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่นชอบ.
        /// </summary>
        internal static string tFavor {
            get {
                return ResourceManager.GetString("tFavor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กลุ่มสินค้า.
        /// </summary>
        internal static string tGroupPdt {
            get {
                return ResourceManager.GetString("tGroupPdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กลุ่มลูกค้า.
        /// </summary>
        internal static string tGrpCst {
            get {
                return ResourceManager.GetString("tGrpCst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โหมดสแกน.
        /// </summary>
        internal static string tModeScan {
            get {
                return ResourceManager.GetString("tModeScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โหมดสัมผัส.
        /// </summary>
        internal static string tModeTouch {
            get {
                return ResourceManager.GetString("tModeTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มีการทำรายการค้างอยู่ ไม่สามารถกลับสู่เมนูหลักได้.
        /// </summary>
        internal static string tMsgCantBack {
            get {
                return ResourceManager.GetString("tMsgCantBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มีการทำรายการค้างอยู่ ไม่สามารถเลือกลูกค้าใหม่ได้.
        /// </summary>
        internal static string tMsgCantSelectCst {
            get {
                return ResourceManager.GetString("tMsgCantSelectCst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มีการทำรายการค้างอยู่ ไม่สามารถเลือกใบสั่งขายได้.
        /// </summary>
        internal static string tMsgCantSO {
            get {
                return ResourceManager.GetString("tMsgCantSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระดับราคาขายต่างกัน ไม่สามารถแก้ไขได้(เปลี่ยนโดยการยกเลิกเอกสาร อย่างเดียว).
        /// </summary>
        internal static string tMsgDiffPriLev {
            get {
                return ResourceManager.GetString("tMsgDiffPriLev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บิลนี้ถูกอ้างอิงไปแล้ว !!!.
        /// </summary>
        internal static string tMsgErrReferBill {
            get {
                return ResourceManager.GetString("tMsgErrReferBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บิลนี้ถูกคืนไปแล้ว !!!.
        /// </summary>
        internal static string tMsgErrRetrunBill {
            get {
                return ResourceManager.GetString("tMsgErrRetrunBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระบบไม่อนุญาต ให้เพิ่ม/แก้ไขรายการ กรณีอ้างถึงบิลขาย.
        /// </summary>
        internal static string tMsgNoEditItemRet {
            get {
                return ResourceManager.GetString("tMsgNoEditItemRet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบข้อมูล หรือยังไม่มีการกำหนดข้อมูล.
        /// </summary>
        internal static string tMsgNotFoundPdt {
            get {
                return ResourceManager.GetString("tMsgNotFoundPdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนคงเหลือ.
        /// </summary>
        internal static string tMsgPdtQtyBalance {
            get {
                return ResourceManager.GetString("tMsgPdtQtyBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนสินค้าคงเหลือไม่เพียงพอ !!!.
        /// </summary>
        internal static string tMsgPdtQtyDef {
            get {
                return ResourceManager.GetString("tMsgPdtQtyDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบเลขที่บิลนี้ !!!.
        /// </summary>
        internal static string tMsgReferBillNotFound {
            get {
                return ResourceManager.GetString("tMsgReferBillNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถทำรายการได้ !!!  เนื่องจากไม่พบข้อมูลสินค้า.
        /// </summary>
        internal static string tMsgSoPdtNotFound {
            get {
                return ResourceManager.GetString("tMsgSoPdtNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบข้อมูลสินค้าในคลังสินค้า !!!.
        /// </summary>
        internal static string tMsgStockNotFoundPdt {
            get {
                return ResourceManager.GetString("tMsgStockNotFoundPdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนสินค้าใหม่.
        /// </summary>
        internal static string tNewQty {
            get {
                return ResourceManager.GetString("tNewQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนสินค้าเดิม.
        /// </summary>
        internal static string tOldQty {
            get {
                return ResourceManager.GetString("tOldQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หน้า.
        /// </summary>
        internal static string tPage {
            get {
                return ResourceManager.GetString("tPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ปรับราคาใหม่.
        /// </summary>
        internal static string tPmtAdjPrice {
            get {
                return ResourceManager.GetString("tPmtAdjPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลด.
        /// </summary>
        internal static string tPmtDis {
            get {
                return ResourceManager.GetString("tPmtDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แถมฟรี.
        /// </summary>
        internal static string tPmtFree {
            get {
                return ResourceManager.GetString("tPmtFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กลุ่มราคาใหม่.
        /// </summary>
        internal static string tPmtPriGrp {
            get {
                return ResourceManager.GetString("tPmtPriGrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กลุ่มราคา.
        /// </summary>
        internal static string tPriGrp {
            get {
                return ResourceManager.GetString("tPriGrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อ้างถึงบิล.
        /// </summary>
        internal static string tRefer {
            get {
                return ResourceManager.GetString("tRefer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คืน.
        /// </summary>
        internal static string tRefund {
            get {
                return ResourceManager.GetString("tRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เช่า.
        /// </summary>
        internal static string tRental {
            get {
                return ResourceManager.GetString("tRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขาย.
        /// </summary>
        internal static string tSale {
            get {
                return ResourceManager.GetString("tSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สแกน.
        /// </summary>
        internal static string tScan {
            get {
                return ResourceManager.GetString("tScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกลูกค้า.
        /// </summary>
        internal static string tSelectCst {
            get {
                return ResourceManager.GetString("tSelectCst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เรียงจาก A-Z.
        /// </summary>
        internal static string tSortAZ {
            get {
                return ResourceManager.GetString("tSortAZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เรียงจาก Z-A.
        /// </summary>
        internal static string tSortZA {
            get {
                return ResourceManager.GetString("tSortZA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเลขโทรศัพท์.
        /// </summary>
        internal static string tTelephone {
            get {
                return ResourceManager.GetString("tTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เกิดเหตุการณ์ ดังนี้ :.
        /// </summary>
        internal static string tTitleEvent {
            get {
                return ResourceManager.GetString("tTitleEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันหมดอายุ :.
        /// </summary>
        internal static string tTitleExpd {
            get {
                return ResourceManager.GetString("tTitleExpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระดับ :.
        /// </summary>
        internal static string tTitleLevel {
            get {
                return ResourceManager.GetString("tTitleLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รับชำระยอดรวมสินค้าเป็นศูนย์.
        /// </summary>
        internal static string tTitleMsgRcvPayZero {
            get {
                return ResourceManager.GetString("tTitleMsgRcvPayZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แต้มคงเหลือ :.
        /// </summary>
        internal static string tTitlePoint {
            get {
                return ResourceManager.GetString("tTitlePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระดับราคา :.
        /// </summary>
        internal static string tTitlePriLev {
            get {
                return ResourceManager.GetString("tTitlePriLev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คืนรายการขาย.
        /// </summary>
        internal static string tTitleReferBill {
            get {
                return ResourceManager.GetString("tTitleReferBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อ้างอิงเอกสารคืน.
        /// </summary>
        internal static string tTitleReferBillRtn {
            get {
                return ResourceManager.GetString("tTitleReferBillRtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใบสั่งขาย :.
        /// </summary>
        internal static string tTitleSO {
            get {
                return ResourceManager.GetString("tTitleSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขรถ.
        /// </summary>
        internal static string tTitleVehVIN {
            get {
                return ResourceManager.GetString("tTitleVehVIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รูปสินค้า.
        /// </summary>
        internal static string tViewPdtImg {
            get {
                return ResourceManager.GetString("tViewPdtImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายการสินค้า.
        /// </summary>
        internal static string tViewPdtList {
            get {
                return ResourceManager.GetString("tViewPdtList", resourceCulture);
            }
        }
    }
}
