//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaPos.Resources_String.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resSeach_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resSeach_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdaPos.Resources_String.Local.resSeach_EN", typeof(resSeach_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Bank.
        /// </summary>
        internal static string tBank {
            get {
                return ResourceManager.GetString("tBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string tCode {
            get {
                return ResourceManager.GetString("tCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Color.
        /// </summary>
        internal static string tColor {
            get {
                return ResourceManager.GetString("tColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose CouponType.
        /// </summary>
        internal static string tCouponType {
            get {
                return ResourceManager.GetString("tCouponType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Customer.
        /// </summary>
        internal static string tCst {
            get {
                return ResourceManager.GetString("tCst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose District.
        /// </summary>
        internal static string tDistrict {
            get {
                return ResourceManager.GetString("tDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string tName {
            get {
                return ResourceManager.GetString("tName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Code.
        /// </summary>
        internal static string tPdtCode {
            get {
                return ResourceManager.GetString("tPdtCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string tPdtName {
            get {
                return ResourceManager.GetString("tPdtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Province.
        /// </summary>
        internal static string tProvince {
            get {
                return ResourceManager.GetString("tProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose SubDistrict.
        /// </summary>
        internal static string tSubDistrict {
            get {
                return ResourceManager.GetString("tSubDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch Group Name.
        /// </summary>
        internal static string tTcgName {
            get {
                return ResourceManager.GetString("tTcgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Branch.
        /// </summary>
        internal static string tTitleBch {
            get {
                return ResourceManager.GetString("tTitleBch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose channel.
        /// </summary>
        internal static string tTitleChannel {
            get {
                return ResourceManager.GetString("tTitleChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Nation.
        /// </summary>
        internal static string tTitleNation {
            get {
                return ResourceManager.GetString("tTitleNation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Product.
        /// </summary>
        internal static string tTitlePdt {
            get {
                return ResourceManager.GetString("tTitlePdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose POS.
        /// </summary>
        internal static string tTitlePos {
            get {
                return ResourceManager.GetString("tTitlePos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Touch Group.
        /// </summary>
        internal static string tTitleTouchGrp {
            get {
                return ResourceManager.GetString("tTitleTouchGrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Unit.
        /// </summary>
        internal static string tUnit {
            get {
                return ResourceManager.GetString("tUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose User.
        /// </summary>
        internal static string tUser {
            get {
                return ResourceManager.GetString("tUser", resourceCulture);
            }
        }
    }
}
