//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaPos.Resources_String.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resSetting_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resSetting_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdaPos.Resources_String.Local.resSetting_EN", typeof(resSetting_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        internal static string tAuthen {
            get {
                return ResourceManager.GetString("tAuthen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear master data.
        /// </summary>
        internal static string tClearData {
            get {
                return ResourceManager.GetString("tClearData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear data error.
        /// </summary>
        internal static string tClearDataErr {
            get {
                return ResourceManager.GetString("tClearDataErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear data success.
        /// </summary>
        internal static string tClearDataSuc {
            get {
                return ResourceManager.GetString("tClearDataSuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brown.
        /// </summary>
        internal static string tClrBrown {
            get {
                return ResourceManager.GetString("tClrBrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string tClrCustom {
            get {
                return ResourceManager.GetString("tClrCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Color.
        /// </summary>
        internal static string tClrDark {
            get {
                return ResourceManager.GetString("tClrDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string tClrGreen {
            get {
                return ResourceManager.GetString("tClrGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Color.
        /// </summary>
        internal static string tClrLight {
            get {
                return ResourceManager.GetString("tClrLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Color.
        /// </summary>
        internal static string tClrNormal {
            get {
                return ResourceManager.GetString("tClrNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        internal static string tClrOrange {
            get {
                return ResourceManager.GetString("tClrOrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink.
        /// </summary>
        internal static string tClrPink {
            get {
                return ResourceManager.GetString("tClrPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sky.
        /// </summary>
        internal static string tClrSky {
            get {
                return ResourceManager.GetString("tClrSky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string tConnect {
            get {
                return ResourceManager.GetString("tConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect database fail.
        /// </summary>
        internal static string tConnFail {
            get {
                return ResourceManager.GetString("tConnFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string tDatabase {
            get {
                return ResourceManager.GetString("tDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group per page.
        /// </summary>
        internal static string tGrpPerPage {
            get {
                return ResourceManager.GetString("tGrpPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input Passcode Complete.
        /// </summary>
        internal static string tInputPwd {
            get {
                return ResourceManager.GetString("tInputPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last bill R.
        /// </summary>
        internal static string tLastBillR {
            get {
                return ResourceManager.GetString("tLastBillR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last bill S.
        /// </summary>
        internal static string tLastBillS {
            get {
                return ResourceManager.GetString("tLastBillS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function per page.
        /// </summary>
        internal static string tMenuPerPage {
            get {
                return ResourceManager.GetString("tMenuPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic.
        /// </summary>
        internal static string tModeStd {
            get {
                return ResourceManager.GetString("tModeStd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch screen.
        /// </summary>
        internal static string tModeTouch {
            get {
                return ResourceManager.GetString("tModeTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waring! Clear Data will delete all Pos data, Sale data and License data in this Pos.
        ///Do you want to continue ?.
        /// </summary>
        internal static string tMsgAskClearData {
            get {
                return ResourceManager.GetString("tMsgAskClearData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial the system will adjust all data to be up to date
        ///Do you want to continue?.
        /// </summary>
        internal static string tMsgAskInitSys {
            get {
                return ResourceManager.GetString("tMsgAskInitSys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please CloseShift before change data.
        /// </summary>
        internal static string tMsgClosedShift {
            get {
                return ResourceManager.GetString("tMsgClosedShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please press &apos;Connect&apos; button..
        /// </summary>
        internal static string tMsgConnDB {
            get {
                return ResourceManager.GetString("tMsgConnDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to server MQ success.
        /// </summary>
        internal static string tMsgConnMQSuccess {
            get {
                return ResourceManager.GetString("tMsgConnMQSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial System Error.
        /// </summary>
        internal static string tMsgInitSysError {
            get {
                return ResourceManager.GetString("tMsgInitSysError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial System Success.
        /// </summary>
        internal static string tMsgInitSysSuccess {
            get {
                return ResourceManager.GetString("tMsgInitSysSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input Url service API2PSMaster and Save.
        /// </summary>
        internal static string tMsgInputAPIMaster {
            get {
                return ResourceManager.GetString("tMsgInputAPIMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input branch code and Save.
        /// </summary>
        internal static string tMsgInputBch {
            get {
                return ResourceManager.GetString("tMsgInputBch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input password for database.
        /// </summary>
        internal static string tMsgInputPwdDB {
            get {
                return ResourceManager.GetString("tMsgInputPwdDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input server database.
        /// </summary>
        internal static string tMsgInputSrvDB {
            get {
                return ResourceManager.GetString("tMsgInputSrvDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input user for database.
        /// </summary>
        internal static string tMsgInputUsrDB {
            get {
                return ResourceManager.GetString("tMsgInputUsrDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found PosCode {0} !!!.
        /// </summary>
        internal static string tMsgPosNotFound {
            get {
                return ResourceManager.GetString("tMsgPosNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save data complete.
        /// </summary>
        internal static string tMsgSaveSuccess {
            get {
                return ResourceManager.GetString("tMsgSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a database name..
        /// </summary>
        internal static string tMsgSelectNameDB {
            get {
                return ResourceManager.GetString("tMsgSelectNameDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database name.
        /// </summary>
        internal static string tNameDB {
            get {
                return ResourceManager.GetString("tNameDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Passcode.
        /// </summary>
        internal static string tPasscode {
            get {
                return ResourceManager.GetString("tPasscode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product per page.
        /// </summary>
        internal static string tPdtPerPage {
            get {
                return ResourceManager.GetString("tPdtPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Passcode Invalid.
        /// </summary>
        internal static string tPwdIncorrect {
            get {
                return ResourceManager.GetString("tPwdIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Database.
        /// </summary>
        internal static string tServerDB {
            get {
                return ResourceManager.GetString("tServerDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string tSetting {
            get {
                return ResourceManager.GetString("tSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Ads Screen.
        /// </summary>
        internal static string tShow2ndScreen {
            get {
                return ResourceManager.GetString("tShow2ndScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string tSuccess {
            get {
                return ResourceManager.GetString("tSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string tTheme {
            get {
                return ResourceManager.GetString("tTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Code.
        /// </summary>
        internal static string tTitleBch {
            get {
                return ResourceManager.GetString("tTitleBch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashier.
        /// </summary>
        internal static string tTitleCashier {
            get {
                return ResourceManager.GetString("tTitleCashier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string tTitleGrp {
            get {
                return ResourceManager.GetString("tTitleGrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial System.
        /// </summary>
        internal static string tTitleInitSys {
            get {
                return ResourceManager.GetString("tTitleInitSys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode windows sale.
        /// </summary>
        internal static string tTitleMode {
            get {
                return ResourceManager.GetString("tTitleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rabbit MQ.
        /// </summary>
        internal static string tTitleMQ {
            get {
                return ResourceManager.GetString("tTitleMQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string tTitleName {
            get {
                return ResourceManager.GetString("tTitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Admin.
        /// </summary>
        internal static string tTitlePasscode {
            get {
                return ResourceManager.GetString("tTitlePasscode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pos.
        /// </summary>
        internal static string tTitlePos {
            get {
                return ResourceManager.GetString("tTitlePos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS Code.
        /// </summary>
        internal static string tTitlePosCode {
            get {
                return ResourceManager.GetString("tTitlePosCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS Type.
        /// </summary>
        internal static string tTitlePosType {
            get {
                return ResourceManager.GetString("tTitlePosType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password MQ.
        /// </summary>
        internal static string tTitlePwdMQ {
            get {
                return ResourceManager.GetString("tTitlePwdMQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server MQ.
        /// </summary>
        internal static string tTitleSvrMQ {
            get {
                return ResourceManager.GetString("tTitleSvrMQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Connent.
        /// </summary>
        internal static string tTitleTestConn {
            get {
                return ResourceManager.GetString("tTitleTestConn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User MQ.
        /// </summary>
        internal static string tTitleUsrMQ {
            get {
                return ResourceManager.GetString("tTitleUsrMQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string tTitleValue {
            get {
                return ResourceManager.GetString("tTitleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual MQ.
        /// </summary>
        internal static string tTitleVirtualMQ {
            get {
                return ResourceManager.GetString("tTitleVirtualMQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccess.
        /// </summary>
        internal static string tUnSuccess {
            get {
                return ResourceManager.GetString("tUnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string tUser {
            get {
                return ResourceManager.GetString("tUser", resourceCulture);
            }
        }
    }
}
