//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaPos.Resources_String.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resTopUp_TH {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resTopUp_TH() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdaPos.Resources_String.Local.resTopUp_TH", typeof(resTopUp_TH).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มูลค่าที่ใช้ได้.
        /// </summary>
        internal static string tAvailable {
            get {
                return ResourceManager.GetString("tAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอดคงเหลือ.
        /// </summary>
        internal static string tBalance {
            get {
                return ResourceManager.GetString("tBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยกเลิกเติมเงิน.
        /// </summary>
        internal static string tCancel {
            get {
                return ResourceManager.GetString("tCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนเงินยกเลิก.
        /// </summary>
        internal static string tCancelAmt {
            get {
                return ResourceManager.GetString("tCancelAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อบัตร.
        /// </summary>
        internal static string tCardName {
            get {
                return ResourceManager.GetString("tCardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเลขบัตร.
        /// </summary>
        internal static string tCardNo {
            get {
                return ResourceManager.GetString("tCardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภท.
        /// </summary>
        internal static string tCardType {
            get {
                return ResourceManager.GetString("tCardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยกเลิก.
        /// </summary>
        internal static string tCmdCancel {
            get {
                return ResourceManager.GetString("tCmdCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยื่นยัน.
        /// </summary>
        internal static string tCmdConfirm {
            get {
                return ResourceManager.GetString("tCmdConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่.
        /// </summary>
        internal static string tCmdNo {
            get {
                return ResourceManager.GetString("tCmdNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มูลค่า.
        /// </summary>
        internal static string tColAmt {
            get {
                return ResourceManager.GetString("tColAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอดเดิม.
        /// </summary>
        internal static string tColBalan {
            get {
                return ResourceManager.GetString("tColBalan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายการ.
        /// </summary>
        internal static string tColDetail {
            get {
                return ResourceManager.GetString("tColDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มัดจำ.
        /// </summary>
        internal static string tDeposit {
            get {
                return ResourceManager.GetString("tDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันหมดอายุ.
        /// </summary>
        internal static string tExp {
            get {
                return ResourceManager.GetString("tExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตรวจสอบมูลค่าและประวัติ.
        /// </summary>
        internal static string tHistory {
            get {
                return ResourceManager.GetString("tHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มีการทำรายการค้างอยู่ ไม่สามารถกลับสู่เมนูหลักได้.
        /// </summary>
        internal static string tMsgCantBack {
            get {
                return ResourceManager.GetString("tMsgCantBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถทำรายการได้ เนื่องจากบัตรยกเลิก.
        /// </summary>
        internal static string tMsgCrdCancel {
            get {
                return ResourceManager.GetString("tMsgCrdCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถทำรายการได้ เนื่องจากบัตรหมดอายุ.
        /// </summary>
        internal static string tMsgCrdExp {
            get {
                return ResourceManager.GetString("tMsgCrdExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถทำรายการได้ เนื่องจากบัตรไม่เคลื่อนไหว.
        /// </summary>
        internal static string tMsgCrdInactive {
            get {
                return ResourceManager.GetString("tMsgCrdInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอดเงินในบัตรหมดอายุ
        ///กรุณากด OK เพื่อเคลียร์ยอดเงินในบัตร และเติมเงิน
        ///หรือ กด Cancel เพื่อยกเลิกการเติมเงิน.
        /// </summary>
        internal static string tMsgCrdValueExp {
            get {
                return ResourceManager.GetString("tMsgCrdValueExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อริสแบนด์ / บัตร.
        /// </summary>
        internal static string tName {
            get {
                return ResourceManager.GetString("tName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเลขริสแบนด์ / บัตร.
        /// </summary>
        internal static string tNo {
            get {
                return ResourceManager.GetString("tNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชำระเงิน.
        /// </summary>
        internal static string tPayment {
            get {
                return ResourceManager.GetString("tPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เงินมัดจำสินค้า.
        /// </summary>
        internal static string tPdtDeposit {
            get {
                return ResourceManager.GetString("tPdtDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวน.
        /// </summary>
        internal static string tQty {
            get {
                return ResourceManager.GetString("tQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายการ.
        /// </summary>
        internal static string tQtyUnit {
            get {
                return ResourceManager.GetString("tQtyUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เงินด่วน.
        /// </summary>
        internal static string tQuick {
            get {
                return ResourceManager.GetString("tQuick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รับเงิน.
        /// </summary>
        internal static string tReceived {
            get {
                return ResourceManager.GetString("tReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทบัตรไม่ตรงตามเงื่อนไข.
        /// </summary>
        internal static string tStaCrdType {
            get {
                return ResourceManager.GetString("tStaCrdType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอดเดิม.
        /// </summary>
        internal static string tTitleColBalance {
            get {
                return ResourceManager.GetString("tTitleColBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอดก่อนคืน.
        /// </summary>
        internal static string tTitleColBeforeBal {
            get {
                return ResourceManager.GetString("tTitleColBeforeBal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอดก่อนชำระ.
        /// </summary>
        internal static string tTitleColBeforePay {
            get {
                return ResourceManager.GetString("tTitleColBeforePay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเลขบัตร.
        /// </summary>
        internal static string tTitleColCardNo {
            get {
                return ResourceManager.GetString("tTitleColCardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แคชเชียร์.
        /// </summary>
        internal static string tTitleColCashier {
            get {
                return ResourceManager.GetString("tTitleColCashier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่.
        /// </summary>
        internal static string tTitleColDate {
            get {
                return ResourceManager.GetString("tTitleColDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอดชำระ.
        /// </summary>
        internal static string tTitleColPay {
            get {
                return ResourceManager.GetString("tTitleColPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอดโปรโมชั่น.
        /// </summary>
        internal static string tTitleColPromo {
            get {
                return ResourceManager.GetString("tTitleColPromo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอดคืน.
        /// </summary>
        internal static string tTitleColReturn {
            get {
                return ResourceManager.GetString("tTitleColReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลำดับ.
        /// </summary>
        internal static string tTitleColSeq {
            get {
                return ResourceManager.GetString("tTitleColSeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ร้านค้า.
        /// </summary>
        internal static string tTitleColShop {
            get {
                return ResourceManager.GetString("tTitleColShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอดเติม.
        /// </summary>
        internal static string tTitleColTopup {
            get {
                return ResourceManager.GetString("tTitleColTopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอดรวม.
        /// </summary>
        internal static string tTitleColTotal {
            get {
                return ResourceManager.GetString("tTitleColTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอดคงเหลือ.
        /// </summary>
        internal static string tTitleColTotalBalance {
            get {
                return ResourceManager.GetString("tTitleColTotalBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภท.
        /// </summary>
        internal static string tTitleColType {
            get {
                return ResourceManager.GetString("tTitleColType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มูลค่า.
        /// </summary>
        internal static string tTitleColValue {
            get {
                return ResourceManager.GetString("tTitleColValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยกเลิก - ยอดโปรโมชั่น.
        /// </summary>
        internal static string tTitleColVoidPromo {
            get {
                return ResourceManager.GetString("tTitleColVoidPromo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยกเลิก-ยอดเติม.
        /// </summary>
        internal static string tTitleColVoidTopup {
            get {
                return ResourceManager.GetString("tTitleColVoidTopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยกเลิกการเติมเงินล่าสุด.
        /// </summary>
        internal static string tTitleVoidTopupL {
            get {
                return ResourceManager.GetString("tTitleVoidTopupL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เติมเงิน.
        /// </summary>
        internal static string tTopup {
            get {
                return ResourceManager.GetString("tTopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รวมเงิน.
        /// </summary>
        internal static string tTotal {
            get {
                return ResourceManager.GetString("tTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มูลค่าริสแบนด์ / บัตร.
        /// </summary>
        internal static string tValue {
            get {
                return ResourceManager.GetString("tValue", resourceCulture);
            }
        }
    }
}
