//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaPos.Resources_String.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resTrade_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resTrade_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdaPos.Resources_String.Local.resTrade_EN", typeof(resTrade_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        internal static string tMode {
            get {
                return ResourceManager.GetString("tMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set 1:1.
        /// </summary>
        internal static string tOneByOne {
            get {
                return ResourceManager.GetString("tOneByOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string tPdtName {
            get {
                return ResourceManager.GetString("tPdtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seq.
        /// </summary>
        internal static string tSeq {
            get {
                return ResourceManager.GetString("tSeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket No..
        /// </summary>
        internal static string tTKNo {
            get {
                return ResourceManager.GetString("tTKNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Qty..
        /// </summary>
        internal static string tTKQty {
            get {
                return ResourceManager.GetString("tTKQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Wristband.
        /// </summary>
        internal static string tTrade {
            get {
                return ResourceManager.GetString("tTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wristband No. / Card No..
        /// </summary>
        internal static string tWBNo {
            get {
                return ResourceManager.GetString("tWBNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wristband Qty..
        /// </summary>
        internal static string tWBQty {
            get {
                return ResourceManager.GetString("tWBQty", resourceCulture);
            }
        }
    }
}
