//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaPos.Resources_String.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resTaxInvoice_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resTaxInvoice_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdaPos.Resources_String.Local.resTaxInvoice_EN", typeof(resTaxInvoice_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string tAddress {
            get {
                return ResourceManager.GetString("tAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        internal static string tAddV1DstCode {
            get {
                return ResourceManager.GetString("tAddV1DstCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H. Number.
        /// </summary>
        internal static string tAddV1No {
            get {
                return ResourceManager.GetString("tAddV1No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Code.
        /// </summary>
        internal static string tAddV1PostCode {
            get {
                return ResourceManager.GetString("tAddV1PostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        internal static string tAddV1PvnCode {
            get {
                return ResourceManager.GetString("tAddV1PvnCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road.
        /// </summary>
        internal static string tAddV1Road {
            get {
                return ResourceManager.GetString("tAddV1Road", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alley.
        /// </summary>
        internal static string tAddV1Soi {
            get {
                return ResourceManager.GetString("tAddV1Soi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub District.
        /// </summary>
        internal static string tAddV1SubDist {
            get {
                return ResourceManager.GetString("tAddV1SubDist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Village.
        /// </summary>
        internal static string tAddV1Village {
            get {
                return ResourceManager.GetString("tAddV1Village", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string tAmt {
            get {
                return ResourceManager.GetString("tAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approvers.
        /// </summary>
        internal static string tApv {
            get {
                return ResourceManager.GetString("tApv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before Tax.
        /// </summary>
        internal static string tB4Vat {
            get {
                return ResourceManager.GetString("tB4Vat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Code.
        /// </summary>
        internal static string tBchCode {
            get {
                return ResourceManager.GetString("tBchCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        internal static string tBranch {
            get {
                return ResourceManager.GetString("tBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Business.
        /// </summary>
        internal static string tBsnType {
            get {
                return ResourceManager.GetString("tBsnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casheir.
        /// </summary>
        internal static string tCasheir {
            get {
                return ResourceManager.GetString("tCasheir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string tCopy {
            get {
                return ResourceManager.GetString("tCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Code.
        /// </summary>
        internal static string tCstCode {
            get {
                return ResourceManager.GetString("tCstCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        internal static string tCstName {
            get {
                return ResourceManager.GetString("tCstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string tDate {
            get {
                return ResourceManager.GetString("tDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        internal static string tDeposit {
            get {
                return ResourceManager.GetString("tDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string tDis {
            get {
                return ResourceManager.GetString("tDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document No..
        /// </summary>
        internal static string tDocNo {
            get {
                return ResourceManager.GetString("tDocNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elaborate.
        /// </summary>
        internal static string tElaborate {
            get {
                return ResourceManager.GetString("tElaborate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establishment.
        /// </summary>
        internal static string tEstab {
            get {
                return ResourceManager.GetString("tEstab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string tFax {
            get {
                return ResourceManager.GetString("tFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        internal static string tFileName {
            get {
                return ResourceManager.GetString("tFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headquarters.
        /// </summary>
        internal static string tHQ {
            get {
                return ResourceManager.GetString("tHQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual.
        /// </summary>
        internal static string tIndividual {
            get {
                return ResourceManager.GetString("tIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string tItem {
            get {
                return ResourceManager.GetString("tItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juristic Person.
        /// </summary>
        internal static string tJuristic {
            get {
                return ResourceManager.GetString("tJuristic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This document has been processed..
        /// </summary>
        internal static string tMsgApproved {
            get {
                return ResourceManager.GetString("tMsgApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input address.
        /// </summary>
        internal static string tMsgInputAdd {
            get {
                return ResourceManager.GetString("tMsgInputAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input document no.
        /// </summary>
        internal static string tMsgInputDoc {
            get {
                return ResourceManager.GetString("tMsgInputDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input customer name.
        /// </summary>
        internal static string tMsgInputName {
            get {
                return ResourceManager.GetString("tMsgInputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input Tax ID.
        /// </summary>
        internal static string tMsgInputTaxNo {
            get {
                return ResourceManager.GetString("tMsgInputTaxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t to print, Becuase document do not create..
        /// </summary>
        internal static string tMsgNotPrint {
            get {
                return ResourceManager.GetString("tMsgNotPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing completed. !!!.
        /// </summary>
        internal static string tMsgPrcComplete {
            get {
                return ResourceManager.GetString("tMsgPrcComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save edit in complete.
        /// </summary>
        internal static string tMsgSave {
            get {
                return ResourceManager.GetString("tMsgSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string tNo {
            get {
                return ResourceManager.GetString("tNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Exempt.
        /// </summary>
        internal static string tNonVat {
            get {
                return ResourceManager.GetString("tNonVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Detail.
        /// </summary>
        internal static string tPdtDetail {
            get {
                return ResourceManager.GetString("tPdtDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Code.
        /// </summary>
        internal static string tPdtID {
            get {
                return ResourceManager.GetString("tPdtID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string tPdtName {
            get {
                return ResourceManager.GetString("tPdtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS.
        /// </summary>
        internal static string tPos {
            get {
                return ResourceManager.GetString("tPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string tPrice {
            get {
                return ResourceManager.GetString("tPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string tQty {
            get {
                return ResourceManager.GetString("tQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive by.
        /// </summary>
        internal static string tReceive {
            get {
                return ResourceManager.GetString("tReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref. Doc..
        /// </summary>
        internal static string tRefDoc {
            get {
                return ResourceManager.GetString("tRefDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        internal static string tRemark {
            get {
                return ResourceManager.GetString("tRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round Rcv..
        /// </summary>
        internal static string tRnd {
            get {
                return ResourceManager.GetString("tRnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saleman.
        /// </summary>
        internal static string tSaleman {
            get {
                return ResourceManager.GetString("tSaleman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send By.
        /// </summary>
        internal static string tSend {
            get {
                return ResourceManager.GetString("tSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seq.
        /// </summary>
        internal static string tSeq {
            get {
                return ResourceManager.GetString("tSeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string tSum {
            get {
                return ResourceManager.GetString("tSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Amount.
        /// </summary>
        internal static string tSumAmt {
            get {
                return ResourceManager.GetString("tSumAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum. Qty..
        /// </summary>
        internal static string tSumQty {
            get {
                return ResourceManager.GetString("tSumQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Invoice.
        /// </summary>
        internal static string tTax {
            get {
                return ResourceManager.GetString("tTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax ID.
        /// </summary>
        internal static string tTaxID {
            get {
                return ResourceManager.GetString("tTaxID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        internal static string tTel {
            get {
                return ResourceManager.GetString("tTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string tTitleAddr1 {
            get {
                return ResourceManager.GetString("tTitleAddr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 1.
        /// </summary>
        internal static string tTitleAddr11 {
            get {
                return ResourceManager.GetString("tTitleAddr11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string tTitleAddr2 {
            get {
                return ResourceManager.GetString("tTitleAddr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 2.
        /// </summary>
        internal static string tTitleAddr21 {
            get {
                return ResourceManager.GetString("tTitleAddr21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After Disc./Chg..
        /// </summary>
        internal static string tTitleAftDisChg {
            get {
                return ResourceManager.GetString("tTitleAftDisChg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string tTitleCst {
            get {
                return ResourceManager.GetString("tTitleCst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name Tax.
        /// </summary>
        internal static string tTitleCstNameTax {
            get {
                return ResourceManager.GetString("tTitleCstNameTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disc./Chg..
        /// </summary>
        internal static string tTitleDisChg {
            get {
                return ResourceManager.GetString("tTitleDisChg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Total.
        /// </summary>
        internal static string tTitleNet {
            get {
                return ResourceManager.GetString("tTitleNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slip No..
        /// </summary>
        internal static string tTitleSlipNo {
            get {
                return ResourceManager.GetString("tTitleSlipNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax No..
        /// </summary>
        internal static string tTitleTaxNo {
            get {
                return ResourceManager.GetString("tTitleTaxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string tTitleTotal {
            get {
                return ResourceManager.GetString("tTitleTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        internal static string tTitleTotalAfVat {
            get {
                return ResourceManager.GetString("tTitleTotalAfVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Payment.
        /// </summary>
        internal static string tTitleTotalPay {
            get {
                return ResourceManager.GetString("tTitleTotalPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Vat.
        /// </summary>
        internal static string tTitleTotalVat {
            get {
                return ResourceManager.GetString("tTitleTotalVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Vatable.
        /// </summary>
        internal static string tTitleTotalVatable {
            get {
                return ResourceManager.GetString("tTitleTotalVatable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Vatable.
        /// </summary>
        internal static string tTitleTotalVatable1 {
            get {
                return ResourceManager.GetString("tTitleTotalVatable1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total WHT Amout.
        /// </summary>
        internal static string tTitleTotalWht {
            get {
                return ResourceManager.GetString("tTitleTotalWht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string tTitleUnit {
            get {
                return ResourceManager.GetString("tTitleUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum. Amt..
        /// </summary>
        internal static string tTotalAmt {
            get {
                return ResourceManager.GetString("tTotalAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string tType {
            get {
                return ResourceManager.GetString("tType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        internal static string tVat {
            get {
                return ResourceManager.GetString("tVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vat Rate.
        /// </summary>
        internal static string tVateRate {
            get {
                return ResourceManager.GetString("tVateRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wristband No. / Card No..
        /// </summary>
        internal static string tWBNo {
            get {
                return ResourceManager.GetString("tWBNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withholding Tax Amt.
        /// </summary>
        internal static string tWhtAmt {
            get {
                return ResourceManager.GetString("tWhtAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withholding Tax.
        /// </summary>
        internal static string tWHTax {
            get {
                return ResourceManager.GetString("tWHTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Tax.
        /// </summary>
        internal static string tWithTax {
            get {
                return ResourceManager.GetString("tWithTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wristband / Card.
        /// </summary>
        internal static string tWristband {
            get {
                return ResourceManager.GetString("tWristband", resourceCulture);
            }
        }
    }
}
